import React, { useEffect, useMemo, useState } from 'react';
import { Star, MessageSquare, Send, ShieldCheck, Loader2, RefreshCw, AlertCircle } from 'lucide-react';
import { useAuth } from '../../lib/AuthContext';
import { supabase } from '../../lib/supabase';

type Review = { id:string; student_id:string; rating:number; comment:string|null; created_at:string; reply_text:string|null; replied_at:string|null; student_name:string; student_avatar:string; };

export const TeacherReviewsPageV2: React.FC = () => {
 const { user } = useAuth(); const [reviews,setReviews]=useState<Review[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [replyId,setReplyId]=useState<string|null>(null); const [reply,setReply]=useState(''); const [saving,setSaving]=useState(false);
 const load=async()=>{ if(!supabase||!user?.uid){setLoading(false);return;} setLoading(true);setError(''); const {data:tp}=await supabase.from('tutor_profiles').select('user_id').eq('user_id',user.uid).maybeSingle(); const tutorId=tp?.user_id||user.uid; const {data,error:e}=await supabase.from('tutor_reviews').select('id,student_id,rating,comment,created_at,reply_text,replied_at').eq('tutor_id',tutorId).order('created_at',{ascending:false}); if(e){setError('تعذر تحميل التقييمات.');setReviews([]);setLoading(false);return;} const ids=[...(data||[]).map((r:any)=>r.student_id)]; let profiles:any[]=[]; if(ids.length){const p=await supabase.from('profiles').select('id,full_name,avatar_url').in('id',ids); if(p.error){setError('تعذر تحميل بيانات الطلاب.');setLoading(false);return;} profiles=p.data||[];} const map=new Map(profiles.map(p=>[p.id,p])); setReviews((data||[]).map((r:any)=>{const p=map.get(r.student_id)||{}; return {...r,student_name:p.full_name||'طالب',student_avatar:p.avatar_url||''};})); setLoading(false); };
 useEffect(()=>{void load();},[user?.uid]);
 useEffect(()=>{if(!supabase||!user?.uid)return; const ch=supabase.channel(`teacher-reviews-${user.uid}`).on('postgres_changes',{event:'*',schema:'public',table:'tutor_reviews',filter:`tutor_id=eq.${user.uid}`},()=>void load()).subscribe(); return()=>{void supabase.removeChannel(ch)}},[user?.uid]);
 const avg=useMemo(()=>reviews.length?(reviews.reduce((s,r)=>s+r.rating,0)/reviews.length).toFixed(1):'0.0',[reviews]);
 const sendReply=async(id:string)=>{if(!supabase||!reply.trim())return;setSaving(true); const {error:e}=await supabase.from('tutor_reviews').update({reply_text:reply.trim(),replied_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('tutor_id',user?.uid||''); if(!e){setReply('');setReplyId(null);await load();} else setError('تعذر حفظ الرد.');setSaving(false);};
 return <div className="space-y-6 text-right" dir="rtl">
  <section className="bg-white border border-slate-200 rounded-3xl p-6 flex justify-between items-center"><div><div className="text-xs font-black text-blue-700 flex items-center gap-2"><Star className="w-4 h-4"/>التقييمات الحقيقية</div><h1 className="text-2xl font-black text-slate-900 mt-2">آراء الطلاب</h1><p className="text-xs text-slate-500 mt-1">التقييمات محفوظة في Supabase وتظهر بعد تجربة حقيقية مع المدرس.</p></div><button onClick={()=>void load()} className="rounded-xl border px-3 py-2 text-xs font-bold flex gap-2"><RefreshCw className="w-4 h-4"/>تحديث</button></section>
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-800 flex gap-2"><AlertCircle className="w-4 h-4"/>{error}</div>}
  <section className="grid grid-cols-2 gap-4"><div className="bg-white border rounded-2xl p-5"><div className="text-xs text-slate-500 font-bold">متوسط التقييم</div><div className="text-3xl font-black mt-1">{avg}</div><div className="flex text-amber-400 mt-2">{[1,2,3,4,5].map(i=><Star key={i} className="w-4 h-4" fill="currentColor"/>)}</div></div><div className="bg-white border rounded-2xl p-5"><div className="text-xs text-slate-500 font-bold">عدد التقييمات</div><div className="text-3xl font-black mt-1">{reviews.length}</div></div></section>
  {loading?<div className="py-14 text-center"><Loader2 className="w-8 h-8 mx-auto animate-spin text-blue-600"/></div>:reviews.length===0?<div className="bg-white border rounded-3xl py-14 text-center text-slate-500"><MessageSquare className="w-10 h-10 mx-auto mb-3 text-slate-300"/><p className="font-bold">لا توجد تقييمات حقيقية بعد</p></div>:<div className="space-y-4">{reviews.map(r=><article key={r.id} className="bg-white border border-slate-200 rounded-3xl p-5"><div className="flex justify-between gap-4"><div className="flex items-center gap-3"><img src={r.student_avatar} className="w-11 h-11 rounded-xl object-cover"/><div><div className="font-black text-sm">{r.student_name}</div><div className="text-[11px] text-slate-400">{new Date(r.created_at).toLocaleDateString('ar-EG')}</div></div></div><div className="flex text-amber-400">{[1,2,3,4,5].map(i=><Star key={i} className={`w-4 h-4 ${i<=r.rating?'fill-current':''}`}/>)}</div></div><p className="mt-4 bg-slate-50 rounded-2xl p-4 text-xs leading-6">{r.comment||'بدون تعليق'}</p><div className="mt-4 flex items-center gap-2 text-[10px] font-bold text-emerald-700"><ShieldCheck className="w-4 h-4"/>تقييم محفوظ في حساب الطالب</div>{r.reply_text?<div className="mt-3 bg-blue-50 border border-blue-100 rounded-2xl p-4 text-xs"><div className="font-black text-blue-800">رد المدرس</div><p className="mt-1 text-blue-900">{r.reply_text}</p></div>:replyId===r.id?<div className="mt-3 space-y-2"><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={3} className="w-full border rounded-2xl p-3 text-xs" placeholder="اكتب ردًا محترمًا للطالب..."/><button disabled={saving||!reply.trim()} onClick={()=>void sendReply(r.id)} className="rounded-xl bg-blue-600 text-white px-4 py-2 text-xs font-black flex gap-2 items-center"><Send className="w-4 h-4"/>{saving?'جاري الحفظ...':'إرسال الرد'}</button></div>:<button onClick={()=>setReplyId(r.id)} className="mt-3 rounded-xl bg-slate-900 text-white px-4 py-2 text-xs font-black">الرد على التقييم</button>}</article>)}</div>}
 </div>;
};
