import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Activity,AlertTriangle,Award,BookOpen,Calendar,ChevronLeft,Clock3,FileCheck2,Layers,MessageCircle,RefreshCw,ScanLine,ShieldCheck,UserPlus,Users,WalletCards}from'lucide-react';
import{useAuth}from'../../lib/AuthContext';
import{supabase}from'../../lib/supabase';
import{loadTeacherGroups,loadTeacherStudents}from'../../lib/teacherStore';
import{StudentGroup,TeacherStudentItem}from'../../types';

interface Props{onNavigate:(path:string)=>void}
type Session={id:string;group_id:string;title:string|null;subject:string|null;session_date:string|null;starts_at:string;ends_at:string;location:string|null;status:string|null};
type Exam={id:string;title:string;exam_date:string;status:string;total_marks:number};

const fmtTime=(value:string)=>new Date(value).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'});
const fmtDate=(value:string)=>new Date(value).toLocaleDateString('ar-EG',{weekday:'long',day:'numeric',month:'long'});

export const TeacherWorkspacePage:React.FC<Props>=({onNavigate})=>{
 const{user}=useAuth(); const teacherId=user?.uid||'';
 const[groups,setGroups]=useState<StudentGroup[]>([]); const[students,setStudents]=useState<TeacherStudentItem[]>([]); const[sessions,setSessions]=useState<Session[]>([]); const[exams,setExams]=useState<Exam[]>([]); const[bookings,setBookings]=useState<any[]>([]); const[assistants,setAssistants]=useState<any[]>([]); const[transfers,setTransfers]=useState(0); const[notes,setNotes]=useState(0); const[loading,setLoading]=useState(true); const[refreshing,setRefreshing]=useState(false); const[notice,setNotice]=useState('');
 const load=useCallback(async()=>{if(!supabase||!teacherId){setLoading(false);return;}setRefreshing(true);setNotice('');try{const[start,studentList]=await Promise.all([loadTeacherGroups(teacherId),loadTeacherStudents(teacherId)]);const[today]=[new Date()];const iso=today.toISOString().slice(0,10);const[{data:s},{data:e},{data:b},{data:a},{count:t},{count:n}]=await Promise.all([supabase.from('lesson_sessions').select('id,group_id,title,subject,session_date,starts_at,ends_at,location,status').eq('tutor_id',teacherId).gte('session_date',iso).order('starts_at',{ascending:true}).limit(8),supabase.from('exams').select('id,title,exam_date,status,total_marks').eq('teacher_id',teacherId).gte('exam_date',iso).order('exam_date',{ascending:true}).limit(5),supabase.from('booking_requests').select('id,student_name,subject,day,time,price,status,created_at').eq('tutor_id',teacherId).eq('status','pending').order('created_at',{ascending:false}).limit(6),supabase.from('teacher_assistants').select('id,assistant_id,status,created_at').eq('teacher_id',teacherId).order('created_at',{ascending:false}).limit(6),supabase.from('group_transfer_requests').select('id',{count:'exact',head:true}).eq('status','pending'),supabase.from('student_notes').select('id',{count:'exact',head:true}).eq('created_by',teacherId)]);setGroups(start||[]);setStudents(studentList||[]);setSessions((s||[])as Session[]);setExams((e||[])as Exam[]);setBookings(b||[]);setAssistants(a||[]);setTransfers(t||0);setNotes(n||0);}catch(err:any){setNotice(err?.message||'تعذر تحميل بيانات مساحة المدرس.')}finally{setLoading(false);setRefreshing(false)}},[teacherId]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!supabase||!teacherId)return;const ch=supabase.channel(`teacher-workspace-${teacherId}`).on('postgres_changes',{event:'*',schema:'public',table:'lesson_sessions',filter:`tutor_id=eq.${teacherId}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'booking_requests',filter:`tutor_id=eq.${teacherId}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'teacher_assistants',filter:`teacher_id=eq.${teacherId}`},()=>void load()).subscribe();return()=>{void supabase.removeChannel(ch)}},[teacherId,load]);
 const activeStudents=students.filter(s=>s.status==='active').length; const attendanceRate=useMemo(()=>{const total=students.reduce((n,s)=>n+Number(s.totalSessions||0),0);const attended=students.reduce((n,s)=>n+Number(s.attendedSessions||0),0);return total?Math.round(attended/total*100):0},[students]); const activeAssistants=assistants.filter(a=>a.status==='active').length; const nextExam=exams[0]; const nextSession=sessions[0];
 const actionItems=[{label:'إدارة الطلاب',hint:`${students.length} سجل`,icon:Users,path:'/teacher/students'},{label:'المجموعات',hint:`${groups.length} مجموعة`,icon:Layers,path:'/teacher/groups'},{label:'فريق المساعدين',hint:`${activeAssistants} نشط`,icon:UserPlus,path:'/teacher/assistants'},{label:'الجلسات والحصص',hint:`${sessions.length} قادمة`,icon:Calendar,path:'/teacher/sessions'},{label:'الامتحانات',hint:`${exams.length} قادمة`,icon:FileCheck2,path:'/teacher/exams'},{label:'دفتر الدرجات',hint:'متابعة الأداء',icon:Award,path:'/teacher/gradebook'}];
 return <div dir="rtl" className="space-y-5 text-right">
  {notice&&<div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-xs font-bold text-red-800 flex items-center gap-2"><AlertTriangle className="w-4 h-4"/>{notice}</div>}
  <header className="rounded-[28px] bg-slate-950 text-white p-5 sm:p-7 overflow-hidden relative"><div className="absolute -left-16 -top-20 w-72 h-72 rounded-full bg-blue-600/20 blur-3xl"/><div className="relative flex flex-col xl:flex-row xl:items-center xl:justify-between gap-6"><div><div className="flex items-center gap-2 text-xs font-bold text-blue-200"><span className="w-2 h-2 rounded-full bg-emerald-400"/> مساحة المدرس المباشرة</div><h1 className="text-2xl sm:text-4xl font-black mt-3">أهلًا يا أستاذ {user?.name||'المدرس'} 👋</h1><p className="text-sm text-slate-300 mt-2 leading-7">{fmtDate(new Date().toISOString())} — كل ما تحتاجه لإدارة يومك التعليمي في مكان واحد.</p><div className="flex flex-wrap gap-2 mt-4"><span className="rounded-full bg-white/10 px-3 py-1.5 text-[11px] font-bold">{user?.profileData?.subject?`مادة ${user.profileData.subject}`:'ملف مدرس'}</span><span className="rounded-full bg-emerald-400/10 text-emerald-200 px-3 py-1.5 text-[11px] font-bold flex items-center gap-1"><ShieldCheck className="w-3.5 h-3.5"/> الحساب متصل</span></div></div><div className="grid grid-cols-2 gap-2 sm:flex"><button onClick={()=>onNavigate('/teacher/scan')} className="rounded-2xl bg-emerald-500 text-slate-950 px-4 py-3 text-xs font-black flex items-center justify-center gap-2"><ScanLine className="w-4 h-4"/> حضور QR</button><button onClick={()=>onNavigate('/teacher/exams')} className="rounded-2xl border border-white/10 bg-white/10 px-4 py-3 text-xs font-bold flex items-center justify-center gap-2"><FileCheck2 className="w-4 h-4"/> امتحان جديد</button></div></div></header>
  <section className="grid grid-cols-2 xl:grid-cols-4 gap-3"><Metric title="الطلاب النشطون" value={activeStudents} meta={`${students.length} في السجل`} icon={<Users/>} action={()=>onNavigate('/teacher/students')}/><Metric title="المجموعات" value={groups.length} meta="المجموعات الحالية" icon={<Layers/>} action={()=>onNavigate('/teacher/groups')}/><Metric title="متوسط الحضور" value={`${attendanceRate}%`} meta={attendanceRate>=85?'وضع ممتاز':'يحتاج متابعة'} icon={<Activity/>} action={()=>onNavigate('/teacher/attendance')}/><Metric title="طلبات تحتاج إجراء" value={bookings.length+transfers} meta={`${bookings.length} حجز • ${transfers} نقل`} icon={<Clock3/>} action={()=>onNavigate('/teacher/enrollment-requests')}/></section>
  <section className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2">{actionItems.map(({label,hint,icon:Icon,path})=><button key={path} onClick={()=>onNavigate(path)} className="rounded-2xl border border-slate-200 bg-white p-3 text-right hover:border-blue-300 hover:shadow-sm transition-all"><div className="w-9 h-9 rounded-xl bg-blue-50 text-blue-700 flex items-center justify-center"><Icon className="w-4 h-4"/></div><div className="mt-3 text-xs font-black text-slate-800">{label}</div><div className="mt-1 text-[10px] text-slate-400">{hint}</div></button>)}</section>
  <div className="grid grid-cols-1 xl:grid-cols-3 gap-5">
   <section className="xl:col-span-2 bg-white rounded-3xl border border-slate-200 p-5"><div className="flex items-center justify-between gap-3 mb-4"><div><h2 className="font-black text-slate-900 flex items-center gap-2"><Calendar className="w-5 h-5 text-blue-600"/> اليوم والجلسات القادمة</h2><p className="text-[11px] text-slate-500 mt-1">لا تفوّت أي حصة أو موعد مهم.</p></div><button onClick={()=>void load()} className="rounded-xl border px-3 py-2 text-[11px] font-black flex items-center gap-1"><RefreshCw className={`w-3.5 h-3.5 ${refreshing?'animate-spin':''}`}/>تحديث</button></div>{loading?<Skeleton/>:sessions.length===0?<Empty icon={<Calendar/>} title="لا توجد جلسات مجدولة حاليًا" action="إدارة الجلسات" onClick={()=>onNavigate('/teacher/sessions')}/>:<div className="space-y-2">{sessions.slice(0,5).map(s=><button key={s.id} onClick={()=>onNavigate(`/teacher/sessions/${s.id}`)} className="w-full flex items-center gap-3 rounded-2xl border border-slate-100 bg-slate-50/70 p-3.5 text-right hover:bg-blue-50/60 hover:border-blue-100"><div className="w-12 h-12 rounded-xl bg-white border flex flex-col items-center justify-center shrink-0"><span className="text-[11px] font-black text-blue-700">{fmtTime(s.starts_at)}</span><span className="text-[9px] text-slate-400">{s.session_date||''}</span></div><div className="min-w-0 flex-1"><div className="text-xs font-black text-slate-900 truncate">{s.title||'حصة تعليمية'}</div><div className="text-[11px] text-slate-500 mt-1">{s.subject||'—'} {s.location?`• ${s.location}`:''}</div></div><ChevronLeft className="w-4 h-4 text-slate-300"/></button>)}</div>}</section>
   <section className="bg-white rounded-3xl border border-slate-200 p-5"><h2 className="font-black text-slate-900 flex items-center gap-2"><FileCheck2 className="w-5 h-5 text-blue-600"/> أقرب امتحان</h2>{nextExam?<div className="mt-4 rounded-2xl bg-slate-950 text-white p-4"><div className="text-xs text-blue-200 font-bold">{nextExam.status==='published'?'منشور':nextExam.status==='draft'?'مسودة':'مجدول'}</div><div className="font-black mt-2 leading-6">{nextExam.title}</div><div className="flex items-center gap-2 mt-4 text-xs text-slate-300"><Calendar className="w-4 h-4"/>{new Date(nextExam.exam_date).toLocaleDateString('ar-EG')}</div><div className="flex items-center gap-2 mt-2 text-xs text-slate-300"><Award className="w-4 h-4"/>{nextExam.total_marks} درجة</div><button onClick={()=>onNavigate('/teacher/exams')} className="w-full mt-4 rounded-xl bg-white text-slate-900 py-2.5 text-xs font-black">فتح إدارة الامتحانات</button></div>:<Empty icon={<FileCheck2/>} title="لا توجد امتحانات قادمة" action="إنشاء امتحان" onClick={()=>onNavigate('/teacher/exams')}/>}</section>
  </div>
  <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
   <section className="bg-white rounded-3xl border border-slate-200 p-5"><div className="flex items-center justify-between"><div><h2 className="font-black">طلبات تحتاج قرار</h2><p className="text-[11px] text-slate-500 mt-1">لا تتركها معلقة.</p></div><button onClick={()=>onNavigate('/teacher/enrollment-requests')} className="text-xs font-black text-blue-700">عرض الكل</button></div><div className="mt-4 space-y-2">{bookings.length===0&&transfers===0?<Empty title="لا توجد طلبات معلقة"/>:<><MiniRow label="طلبات حجز جديدة" value={bookings.length} onClick={()=>onNavigate('/teacher/dashboard')}/><MiniRow label="طلبات نقل" value={transfers} onClick={()=>onNavigate('/teacher/transfers')}/></>}</div></section>
   <section className="bg-white rounded-3xl border border-slate-200 p-5"><div className="flex items-center justify-between"><div><h2 className="font-black flex items-center gap-2"><UserPlus className="w-5 h-5 text-blue-600"/> فريق المساعدين</h2><p className="text-[11px] text-slate-500 mt-1">إدارة الفريق والصلاحيات.</p></div><button onClick={()=>onNavigate('/teacher/assistants')} className="text-xs font-black text-blue-700">إدارة</button></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-[11px] text-blue-700 font-bold">نشطون</div><div className="text-2xl font-black text-slate-900 mt-1">{activeAssistants}</div></div><div className="rounded-2xl bg-amber-50 p-4"><div className="text-[11px] text-amber-700 font-bold">ملاحظات طلاب</div><div className="text-2xl font-black text-slate-900 mt-1">{notes}</div></div></div><button onClick={()=>onNavigate('/teacher/assistants')} className="w-full mt-3 rounded-xl border py-2.5 text-xs font-black">البحث عن مساعد جديد</button></section>
   <section className="bg-white rounded-3xl border border-slate-200 p-5"><h2 className="font-black flex items-center gap-2"><WalletCards className="w-5 h-5 text-blue-600"/> المال والمتابعة</h2><div className="mt-4 space-y-2"><MiniRow label="المدفوعات" value="فتح" onClick={()=>onNavigate('/teacher/payments')}/><MiniRow label="المواعيد المتاحة" value="إدارة" onClick={()=>onNavigate('/teacher/availability')}/><MiniRow label="التقييمات" value="مراجعة" onClick={()=>onNavigate('/teacher/reviews')}/><MiniRow label="الملاحظات والسلوك" value={`${notes}`} onClick={()=>onNavigate('/teacher/student-notes')}/></div></section>
  </div>
  <section className="rounded-3xl border border-blue-100 bg-blue-50/70 p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><div className="text-xs font-black text-blue-900">تحتاج مساعدة أو تواصل سريع؟</div><div className="text-[11px] text-blue-700 mt-1">الرسائل والإشعارات متاحة دائمًا من القائمة الجانبية.</div></div><div className="flex gap-2"><button onClick={()=>onNavigate('/teacher/messages')} className="rounded-xl bg-white border border-blue-100 px-4 py-2.5 text-xs font-black text-blue-800 flex items-center gap-2"><MessageCircle className="w-4 h-4"/>الرسائل</button><button onClick={()=>onNavigate('/teacher/notifications')} className="rounded-xl bg-blue-700 text-white px-4 py-2.5 text-xs font-black">الإشعارات</button></div></section>
 </div>;
};

function Metric({title,value,meta,icon,action}:{title:string;value:string|number;meta:string;icon:React.ReactNode;action:()=>void}){return <button onClick={action} className="bg-white border border-slate-200 rounded-2xl p-4 text-right hover:border-blue-300 hover:shadow-sm transition-all"><div className="flex items-center justify-between"><span className="text-[11px] font-bold text-slate-500">{title}</span><span className="text-blue-600">{React.cloneElement(icon as React.ReactElement,{className:'w-4 h-4'})}</span></div><div className="text-2xl font-black text-slate-950 mt-2">{value}</div><div className="text-[10px] text-slate-400 mt-1">{meta}</div></button>}
function MiniRow({label,value,onClick}:{label:string;value:string|number;onClick:()=>void}){return <button onClick={onClick} className="w-full rounded-2xl border border-slate-100 bg-slate-50 px-4 py-3 flex items-center justify-between text-right"><span className="text-xs font-bold text-slate-700">{label}</span><span className="text-xs font-black text-blue-700">{value}</span></button>}
function Empty({title,icon,action,onClick}:{title:string;icon?:React.ReactNode;action?:string;onClick?:()=>void}){return <div className="py-7 text-center"><div className="w-11 h-11 mx-auto rounded-2xl bg-slate-100 text-slate-400 flex items-center justify-center">{icon||<Activity className="w-5 h-5"/>}</div><div className="text-xs font-bold text-slate-500 mt-3">{title}</div>{action&&onClick&&<button onClick={onClick} className="mt-3 rounded-xl bg-slate-950 text-white px-4 py-2 text-[11px] font-black">{action}</button>}</div>}
function Skeleton(){return <div className="space-y-2">{[1,2,3].map(i=><div key={i} className="h-16 rounded-2xl bg-slate-100 animate-pulse"/>)}</div>}
