import express from 'express';
import path from 'path';
import crypto from 'crypto';
import nodemailer from 'nodemailer';
import { createServer as createViteServer } from 'vite';

const app = express();
const PORT = Number(process.env.PORT || 3000);
app.set('trust proxy', 1);
app.use((req, res, next) => { res.setHeader('X-Frame-Options','SAMEORIGIN'); res.setHeader('X-Content-Type-Options','nosniff'); res.setHeader('Referrer-Policy','strict-origin-when-cross-origin'); res.setHeader('Permissions-Policy','camera=(self), microphone=(self), geolocation=()'); if(req.path.startsWith('/api/')) res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate'); res.removeHeader('X-Powered-By'); next(); });
app.use(express.json({limit:'1mb'}));

function env(name:string){const v=process.env[name]?.trim(); if(!v) throw new Error(`Missing required environment variable: ${name}`); return v;}
const OFFICIAL_ADMIN_EMAIL=(process.env.OFFICIAL_ADMIN_EMAIL?.trim().toLowerCase())||'hasstysupport@gmail.com';
const ADMIN_ROUTE_PREFIX=(process.env.ADMIN_ROUTE_PREFIX?.trim())||'/sys-ctrl-98xf-vault';
const SMTP_HOST=(process.env.SMTP_HOST?.trim())||'smtp.gmail.com';
const SMTP_PORT=Number(process.env.SMTP_PORT||465);
let transporter:nodemailer.Transporter|null=null;
function getTransporter(){const user=env('SMTP_USER'); const pass=env('SMTP_PASS'); if(!transporter) transporter=nodemailer.createTransport({host:SMTP_HOST,port:SMTP_PORT,secure:SMTP_PORT===465,auth:{user,pass},tls:{rejectUnauthorized:true}}); return transporter;}
async function sendMail(to:string,subject:string,text:string){try{await getTransporter().sendMail({from:`"منصة حِصّتي" <${env('SMTP_USER')}>`,to,subject,text,html:`<div dir="rtl"><p>${text.replace(/\n/g,'<br>')}</p></div>`});return true;}catch(e){console.error('SMTP delivery failed:',e instanceof Error?e.message:'unknown error');return false;}}

interface Rate{count:number;first:number;blocked?:number} interface Otp{requestId:string;number:string;code:string;expiresAt:number;attempts:number} interface EmailOtp{requestId:string;email:string;uid:string;role:string;code:string;expiresAt:number;attempts:number} interface AdminLink{token:string;code:string;expiresAt:number;used:boolean} interface TokenPayload{uid:string;email:string;role:string;emailVerified:boolean;exp:number;iat:number}
const otp=new Map<string,Otp>(); const emailOtp=new Map<string,EmailOtp>(); const admins=new Map<string,AdminLink>(); const ipRates=new Map<string,Rate>(); const phoneRates=new Map<string,Rate>(); const emailRates=new Map<string,Rate>();
function limit(key:string,store:Map<string,Rate>){const now=Date.now();let r=store.get(key);if(!r){store.set(key,{count:1,first:now});return{ok:true};}if(r.blocked&&now<r.blocked)return{ok:false,wait:Math.ceil((r.blocked-now)/1000)};if(now-r.first>3600000){store.set(key,{count:1,first:now});return{ok:true};}r.count++;if(r.count>4){r.blocked=now+1800000;return{ok:false,wait:1800};}return{ok:true};}
setInterval(()=>{const n=Date.now();for(const s of [otp,emailOtp,admins])for(const[k,v]of s)if(n>v.expiresAt)s.delete(k);},60000).unref();
function egyptian(raw:string){let n=String(raw).replace(/\D/g,'');if(n.startsWith('0020'))n=n.slice(2);else if(n.startsWith('0'))n=`20${n.slice(1)}`;else if(!n.startsWith('20')&&n.length===10)n=`20${n}`;return n;}
function ip(req:express.Request){return req.ip||req.socket.remoteAddress||'unknown';}
function sign(p:Omit<TokenPayload,'iat'>){const s=env('AUTH_TOKEN_SECRET');const h=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url');const b=Buffer.from(JSON.stringify({...p,iat:Math.floor(Date.now()/1000)})).toString('base64url');const sig=crypto.createHmac('sha256',s).update(`${h}.${b}`).digest('base64url');return `${h}.${b}.${sig}`;}
function verify(t:string){try{const s=env('AUTH_TOKEN_SECRET');const [h,b,sig]=t.split('.');if(!h||!b||!sig)return{valid:false,error:'Malformed token'};const exp=crypto.createHmac('sha256',s).update(`${h}.${b}`).digest('base64url');const a=Buffer.from(sig),c=Buffer.from(exp);if(a.length!==c.length||!crypto.timingSafeEqual(a,c))return{valid:false,error:'Invalid signature'};const p=JSON.parse(Buffer.from(b,'base64url').toString())as TokenPayload;if(!p.exp||p.exp<Math.floor(Date.now()/1000))return{valid:false,error:'Token expired'};return{valid:true,payload:p};}catch(e){return{valid:false,error:e instanceof Error?e.message:'Token verification failed'};}}
async function wa(pathname:string,init:RequestInit,timeout=8000){const base=env('WHATSAPP_SERVER_URL').replace(/\/$/,'');const key=env('WHATSAPP_API_KEY');const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{return await fetch(`${base}${pathname}`,{...init,headers:{...(init.headers||{}),'X-API-Key':key},signal:c.signal});}finally{clearTimeout(t);}}

app.get(['/api/whatsapp/status','/api/v1/status'],async(_q,res)=>{try{const r=await wa('/api/v1/status',{method:'GET'},4000);const d=await r.json().catch(()=>({}));const connected=d.whatsapp==='connected'||d.success===true;return res.status(r.status||200).json({success:connected,connected,data:d});}catch(e){return res.status(503).json({success:false,connected:false,error:e instanceof Error?e.message:'WhatsApp unavailable'});}});
app.post(['/api/whatsapp/send','/api/v1/send/text'],async(req,res)=>{try{const{number,message}=req.body||{};if(!number||!message)return res.status(400).json({success:false,error:'Number and message are required'});const r=await wa('/api/v1/send/text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({number:egyptian(number),message})});const d=await r.json().catch(()=>({}));return res.status(r.status).json({success:r.ok&&d.success!==false,data:d});}catch(e){return res.status(503).json({success:false,error:e instanceof Error?e.message:'WhatsApp send failed'});}});
app.post('/api/v1/send/interactive',async(req,res)=>{try{const{number,text,footer,buttons,title,sections}=req.body||{};if(!number||!text)return res.status(400).json({success:false,error:'Number and text are required'});const r=await wa('/api/v1/send/interactive',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({number:egyptian(number),text,footer,buttons,title,sections})});const d=await r.json().catch(()=>({}));return res.status(r.status).json({success:r.ok&&d.success!==false,data:d});}catch(e){return res.status(503).json({success:false,error:e instanceof Error?e.message:'Interactive send failed'});}});

app.post('/api/otp/send',async(req,res)=>{try{const{number,purpose}=req.body||{};if(!number)return res.status(400).json({success:false,error:'رقم الهاتف مطلوب'});const n=egyptian(number);for(const c of [limit(`ip:${ip(req)}`,ipRates),limit(`phone:${n}`,phoneRates)])if(!c.ok)return res.status(429).json({success:false,error:'تم تجاوز حد طلبات التحقق مؤقتاً.',waitSeconds:c.wait});const code=crypto.randomInt(100000,1000000).toString();const requestId=`req_${Date.now()}_${crypto.randomBytes(8).toString('hex')}`;otp.set(requestId,{requestId,number:n,code,expiresAt:Date.now()+300000,attempts:0});let sent=false;try{const r=await wa('/api/v1/send/text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({number:n,message:`منصة حِصّتي — كود التحقق: ${code}\nهذا الرمز صالح لمدة 5 دقائق.`})},7000);const d=await r.json().catch(()=>({}));sent=r.ok&&d.success!==false;}catch{}return res.json({success:true,requestId,formattedNumber:n,whatsappSent:sent,expiresInSeconds:300,purpose:purpose||'login'});}catch(e){return res.status(500).json({success:false,error:e instanceof Error?e.message:'OTP request failed'});}});
app.post('/api/otp/verify',(req,res)=>{const{id,requestId,code}=req.body||{};const key=String(requestId||id||'');const e=otp.get(key);if(!e||Date.now()>e.expiresAt){if(e)otp.delete(key);return res.status(400).json({success:false,verified:false,error:'انتهت صلاحية رمز التحقق.'});}e.attempts++;if(e.attempts>4){otp.delete(key);return res.status(429).json({success:false,verified:false,error:'تم تجاوز الحد الأقصى للمحاولات.'});}if(e.code!==String(code||'').trim())return res.status(400).json({success:false,verified:false,error:`كود التحقق غير صحيح. متبقي ${4-e.attempts} محاولات.`});otp.delete(key);return res.json({success:true,verified:true,number:e.number});});

app.post(['/api/auth/otp/send-email','/api/auth/send-verification-code'],async(req,res)=>{try{const{email,uid,name,role,purpose}=req.body||{};if(!email||typeof email!=='string'||!email.includes('@'))return res.status(400).json({success:false,error:'البريد الإلكتروني غير صحيح أو مطلوب'});const clean=email.trim().toLowerCase();const c=limit(`email:${clean}`,emailRates);if(!c.ok)return res.status(429).json({success:false,error:'تم تجاوز حد طلبات التحقق مؤقتاً.',waitSeconds:c.wait});const code=crypto.randomInt(100000,1000000).toString();const requestId=`vreq_${Date.now()}_${crypto.randomBytes(8).toString('hex')}`;emailOtp.set(requestId,{requestId,email:clean,uid:uid||'',role:role||'student',code,expiresAt:Date.now()+300000,attempts:0});const appUrl=process.env.PUBLIC_APP_URL||'https://hassty.vercel.app';const link=`${appUrl}/verify-email?req=${encodeURIComponent(requestId)}&code=${encodeURIComponent(code)}`;const sent=await sendMail(clean,`رمز أمان منصة حِصّتي: ${code}`,`مرحباً ${name||''}\nرمز التحقق: ${code}\n${link}\nصلاحية الرمز: 5 دقائق.`);const[l,d]=clean.split('@');return res.status(sent?200:503).json({success:sent,requestId,email:clean,maskedEmail:`${l[0]}***${l[l.length-1]}@${d}`,emailSent:sent,expiresInSeconds:300,purpose:purpose||'verification'});}catch(e){return res.status(503).json({success:false,error:e instanceof Error?e.message:'Email service unavailable'});}});
app.post(['/api/auth/otp/verify-email','/api/auth/verify-code'],(req,res)=>{const{requestId,code,email}=req.body||{};const e=emailOtp.get(String(requestId||''));if(!e||Date.now()>e.expiresAt){if(e)emailOtp.delete(String(requestId));return res.status(400).json({success:false,verified:false,error:'انتهت صلاحية كود التحقق.'});}e.attempts++;if(e.attempts>5){emailOtp.delete(String(requestId));return res.status(429).json({success:false,verified:false,error:'تم تجاوز الحد الأقصى للمحاولات.'});}if(e.code!==String(code||'').trim())return res.status(400).json({success:false,verified:false,error:'رمز التحقق غير صحيح.'});emailOtp.delete(String(requestId));const token=sign({uid:e.uid,email:email||e.email,role:e.role,emailVerified:true,exp:Math.floor(Date.now()/1000)+604800});return res.json({success:true,verified:true,token,sessionToken:token,uid:e.uid,email:email||e.email,emailVerified:true});});
app.post('/api/auth/verify-token',(req,res)=>{const auth=String(req.headers.authorization||'');const token=auth.startsWith('Bearer ')?auth.slice(7):req.body?.token;if(!token)return res.status(401).json({valid:false,error:'Authorization token is required'});const r=verify(String(token));if(!r.valid)return res.status(401).json({valid:false,error:r.error});if(req.body?.uid&&req.body.uid!==r.payload?.uid)return res.status(403).json({valid:false,error:'UID mismatch with token claims'});return res.json({valid:true,payload:r.payload});});
app.post('/api/auth/check-data-ownership',(_req,res)=>res.status(410).json({authorized:false,error:'This endpoint is retired. Use Supabase RLS ownership checks.'}));

app.post('/api/admin/request-access-link',async(req,res)=>{try{const target=String(req.body?.targetEmail||OFFICIAL_ADMIN_EMAIL).trim().toLowerCase();if(target!==OFFICIAL_ADMIN_EMAIL)return res.status(403).json({success:false,error:'غير مصرح بهذا البريد الإداري.'});const token=crypto.randomBytes(32).toString('hex');const code=crypto.randomInt(100000,1000000).toString();const entry={token,code,expiresAt:Date.now()+3600000,used:false};admins.set(token,entry);admins.set(code,entry);const url=`${process.env.PUBLIC_APP_URL||'https://hassty.vercel.app'}${ADMIN_ROUTE_PREFIX}?authKey=${encodeURIComponent(token)}`;const sent=await sendMail(OFFICIAL_ADMIN_EMAIL,'دخول إداري آمن — حِصّتي',`رمز الدخول: ${code}\n${url}\nصلاحية الرابط: 60 دقيقة.`);return res.status(sent?200:503).json({success:sent,targetEmail:OFFICIAL_ADMIN_EMAIL,maskedEmail:'h***t@gmail.com',emailSent:sent,expiresInSeconds:3600});}catch(e){return res.status(503).json({success:false,error:e instanceof Error?e.message:'Admin email service unavailable'});}});
app.post('/api/admin/verify-magic-token',(req,res)=>{const key=String(req.body?.token||req.body?.code||'').trim();const e=admins.get(key);if(!e)return res.status(401).json({valid:false,error:'كود أو رابط الدخول غير صالح.'});if(Date.now()>e.expiresAt){admins.delete(e.token);admins.delete(e.code);return res.status(401).json({valid:false,error:'انتهت صلاحية كود الدخول.'});}if(e.used)return res.status(401).json({valid:false,error:'تم استخدام هذا الكود مسبقاً.'});e.used=true;admins.delete(e.token);admins.delete(e.code);const sessionToken=sign({uid:'admin_master_uid',email:OFFICIAL_ADMIN_EMAIL,role:'admin',emailVerified:true,exp:Math.floor(Date.now()/1000)+86400});return res.json({valid:true,sessionToken,email:OFFICIAL_ADMIN_EMAIL,expiresInSeconds:86400});});

app.get('/robots.txt',(_q,res)=>res.sendFile(path.join(process.cwd(),'public','robots.txt')));
app.get('/sitemap.xml',(_q,res)=>{res.type('application/xml');res.sendFile(path.join(process.cwd(),'public','sitemap.xml'));});
async function start(){if(process.env.NODE_ENV!=='production'){const vite=await createViteServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);}else{const dist=path.join(process.cwd(),'dist');app.use(express.static(dist));app.get('*',(_q,res)=>res.sendFile(path.join(dist,'index.html')));}app.listen(PORT,'0.0.0.0',()=>console.log(`Hassty server listening on ${PORT}`));}
start().catch(e=>{console.error('Hassty server failed to start:',e);process.exit(1);});
