import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, BookOpen, CalendarDays, Check, CheckCircle2, Clock3, FileText, Filter, MessageCircle, Paperclip, Send, Star, Trash2, UserRound, X } from 'lucide-react';
import { useAuth } from '../lib/AuthContext';
import { supabase } from '../lib/supabase';

const shell = 'space-y-5 text-right font-[\'IBM_Plex_Sans_Arabic\',sans-serif]';
const card = 'bg-white border border-gray-200 rounded-3xl p-5 shadow-xs';

export const NotificationsPage: React.FC<{ onNavigate?: (path: string) => void }> = ({ onNavigate }) => {
  const { user } = useAuth();
  const [items, setItems] = useState<any[]>([]);
  const [filter, setFilter] = useState('all');
  const [loading, setLoading] = useState(true);

  const load = async () => {
    if (!supabase || !user?.uid) return;
    const q = supabase.from('notifications').select('*').eq('user_id', user.uid).order('created_at', { ascending: false }).limit(100);
    const { data, error } = await q;
    if (!error) setItems(data || []);
    setLoading(false);
  };
  useEffect(() => {
    void load();
    if (!supabase || !user?.uid) return;
    const channel = supabase.channel(`notifications:${user.uid}`).on('postgres_changes', { event: '*', schema: 'public', table: 'notifications', filter: `user_id=eq.${user.uid}` }, () => void load()).subscribe();
    return () => { void supabase.removeChannel(channel); };
  }, [user?.uid]);

  const visible = filter === 'unread' ? items.filter((x) => !x.read_at) : filter === 'all' ? items : items.filter((x) => x.type === filter);
  const unread = items.filter((x) => !x.read_at).length;
  const markRead = async (id: string) => {
    if (!supabase) return;
    await supabase.from('notifications').update({ read_at: new Date().toISOString() }).eq('id', id).eq('user_id', user?.uid || '');
    setItems((p) => p.map((x) => x.id === id ? { ...x, read_at: new Date().toISOString() } : x));
  };
  const markAll = async () => {
    if (!supabase || !user?.uid) return;
    await supabase.from('notifications').update({ read_at: new Date().toISOString() }).eq('user_id', user.uid).is('read_at', null);
    setItems((p) => p.map((x) => ({ ...x, read_at: x.read_at || new Date().toISOString() })));
  };
  const remove = async (id: string) => {
    if (!supabase) return;
    await supabase.from('notifications').delete().eq('id', id).eq('user_id', user?.uid || '');
    setItems((p) => p.filter((x) => x.id !== id));
  };

  return <div className={shell} dir="rtl">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-2xl font-black text-[#1E3A8A]">مركز الإشعارات 🔔</h1><p className="text-sm text-gray-500 mt-1">كل تنبيهات الحساب في مكان واحد — {unread} غير مقروء</p></div><button onClick={markAll} className="px-4 py-2 rounded-xl bg-[#EFF6FF] text-[#2563EB] text-xs font-black">تحديد الكل كمقروء</button></div>
    <div className="flex flex-wrap gap-2">{['all','unread','attendance','booking','grade','assignment','reminder','system'].map((f) => <button key={f} onClick={() => setFilter(f)} className={`px-3 py-2 rounded-xl text-xs font-bold border ${filter===f?'bg-[#2563EB] text-white border-[#2563EB]':'bg-white text-gray-600 border-gray-200'}`}>{f==='all'?'الكل':f==='unread'?'غير مقروء':'#'+f}</button>)}</div>
    <div className={card}>{loading ? <div className="py-10 text-center text-sm text-gray-500">جاري تحميل الإشعارات...</div> : visible.length === 0 ? <div className="py-12 text-center text-sm text-gray-400">لا توجد إشعارات في هذا القسم.</div> : <div className="divide-y divide-gray-100">{visible.map((n) => <div key={n.id} className={`py-4 flex gap-3 ${!n.read_at?'bg-blue-50/40 rounded-2xl px-3':''}`}><div className="w-10 h-10 rounded-xl bg-[#EFF6FF] text-[#2563EB] flex items-center justify-center shrink-0"><BellIcon /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h3 className="text-sm font-black text-[#1F2937]">{n.title}</h3><span className="text-[10px] text-gray-400 whitespace-nowrap">{new Date(n.created_at).toLocaleString('ar-EG')}</span></div><p className="text-xs text-gray-600 mt-1 leading-6">{n.message}</p>{n.link && <button onClick={() => { void markRead(n.id); onNavigate?.(n.link); }} className="mt-2 text-xs font-bold text-[#2563EB]">فتح المرتبط ←</button>}</div><div className="flex flex-col gap-1"><button onClick={() => void markRead(n.id)} className="p-2 rounded-lg hover:bg-gray-100" title="مقروء"><Check className="w-4 h-4 text-gray-400" /></button><button onClick={() => void remove(n.id)} className="p-2 rounded-lg hover:bg-red-50" title="حذف"><Trash2 className="w-4 h-4 text-red-400" /></button></div></div>)}</div>}</div>
  </div>;
};
const BellIcon = () => <span className="text-lg">🔔</span>;

export const CalendarPage: React.FC = () => {
  const { user } = useAuth();
  const [sessions, setSessions] = useState<any[]>([]);
  const [events, setEvents] = useState<any[]>([]);
  useEffect(() => { const run = async () => { if (!supabase || !user?.uid) return; const [{data:s},{data:e}] = await Promise.all([supabase.from('lesson_sessions').select('*').order('starts_at'), supabase.from('calendar_events').select('*').eq('user_id', user.uid).order('starts_at')]); setSessions(s||[]); setEvents(e||[]); }; void run(); }, [user?.uid]);
  const all = [...sessions.map((s)=>({...s,_type:'lesson'})), ...events.map((e)=>({...e,_type:e.event_type}))].sort((a,b)=>new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime());
  return <div className={shell} dir="rtl"><div><h1 className="text-2xl font-black text-[#1E3A8A]">التقويم الموحد 📅</h1><p className="text-sm text-gray-500 mt-1">الحصص والحجوزات والاختبارات والواجبات والدفعات والتذكيرات.</p></div><div className={card}>{all.length===0?<div className="py-12 text-center text-gray-400">لا توجد أحداث مجدولة حاليًا.</div>:<div className="grid gap-3">{all.map((x,i)=><div key={`${x.id}-${i}`} className="p-4 rounded-2xl border border-gray-100 bg-gray-50/70 flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-white flex items-center justify-center text-[#2563EB]"><CalendarDays className="w-5 h-5"/></div><div className="flex-1"><div className="flex items-center justify-between gap-2"><h3 className="font-black text-sm">{x.title}</h3><span className="text-[10px] text-gray-500">{new Date(x.starts_at).toLocaleString('ar-EG')}</span></div><p className="text-xs text-gray-500 mt-1">{x.subject||x.description||x.location||''}</p><span className="inline-flex mt-2 px-2 py-1 rounded-lg text-[10px] font-bold bg-white border border-gray-200">{x._type}</span></div></div>)}</div>}</div></div>;
};

export const MessagesPage: React.FC = () => {
  const { user } = useAuth();
  const [threads,setThreads]=useState<any[]>([]); const [selected,setSelected]=useState<any|null>(null); const [messages,setMessages]=useState<any[]>([]); const [text,setText]=useState('');
  const loadThreads=async()=>{ if(!supabase||!user?.uid)return; const {data}=await supabase.from('chat_threads').select('*').or(`student_id.eq.${user.uid},teacher_id.eq.${user.uid},parent_id.eq.${user.uid}`).order('last_message_at',{ascending:false}); setThreads(data||[]); };
  useEffect(()=>{void loadThreads();},[user?.uid]);
  useEffect(()=>{ if(!supabase||!selected)return; const load=async()=>{const {data}=await supabase.from('chat_messages').select('*').eq('thread_id',selected.id).order('created_at',{ascending:true});setMessages(data||[])};void load();const ch=supabase.channel(`chat:${selected.id}`).on('postgres_changes',{event:'*',schema:'public',table:'chat_messages',filter:`thread_id=eq.${selected.id}`},()=>void load());ch.subscribe();return()=>{void supabase.removeChannel(ch)}; },[selected?.id]);
  const send=async()=>{if(!supabase||!user?.uid||!selected||!text.trim())return; await supabase.from('chat_messages').insert({thread_id:selected.id,sender_id:user.uid,body:text.trim()}); await supabase.from('chat_threads').update({last_message_at:new Date().toISOString()}).eq('id',selected.id); setText('');};
  const startSupport=async()=>{if(!supabase||!user?.uid)return;const {data}=await supabase.from('chat_threads').insert({is_support:true,student_id:user.role==='student'?user.uid:null,parent_id:user.role==='parent'?user.uid:null}).select('*').single();if(data){setThreads(p=>[data,...p]);setSelected(data)}};
  return <div className={shell} dir="rtl"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-black text-[#1E3A8A]">الرسائل 💬</h1><p className="text-sm text-gray-500 mt-1">محادثات مباشرة مع المدرسين والدعم.</p></div><button onClick={startSupport} className="px-4 py-2 rounded-xl bg-[#2563EB] text-white text-xs font-black">محادثة مع الدعم</button></div><div className="grid lg:grid-cols-[280px_1fr] gap-4"><div className={card}>{threads.length===0?<p className="text-sm text-gray-400 py-8 text-center">لا توجد محادثات.</p>:threads.map(t=><button key={t.id} onClick={()=>setSelected(t)} className={`w-full text-right p-3 rounded-2xl mb-2 border ${selected?.id===t.id?'bg-blue-50 border-blue-200':'bg-gray-50 border-gray-100'}`}><div className="font-black text-sm">{t.is_support?'دعم حِصّتي':'محادثة تعليمية'}</div><div className="text-[10px] text-gray-500 mt-1">{new Date(t.last_message_at).toLocaleString('ar-EG')}</div></button>)}</div><div className={`${card} min-h-[520px] flex flex-col`}>{!selected?<div className="flex-1 flex items-center justify-center text-sm text-gray-400">اختر محادثة للبدء.</div>:<><div className="pb-3 border-b border-gray-100"><h3 className="font-black">{selected.is_support?'دعم حِصّتي':'المحادثة'}</h3></div><div className="flex-1 overflow-y-auto py-4 space-y-2">{messages.map(m=><div key={m.id} className={`max-w-[80%] p-3 rounded-2xl text-sm ${m.sender_id===user?.uid?'bg-[#2563EB] text-white mr-auto':'bg-gray-100 text-gray-800 ml-auto'}`}><div>{m.body}</div><span className="block text-[9px] opacity-70 mt-1">{new Date(m.created_at).toLocaleTimeString('ar-EG')}</span></div>)}</div><div className="pt-3 border-t border-gray-100 flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}} className="flex-1 rounded-2xl border border-gray-200 px-4 py-3 text-sm" placeholder="اكتب رسالتك..."/><button onClick={()=>void send()} className="w-12 h-12 rounded-2xl bg-[#2563EB] text-white flex items-center justify-center"><Send className="w-5 h-5"/></button></div></>}</div></div></div>;
};

export const AssignmentsPage: React.FC = () => {
  const { user } = useAuth(); const isTeacher=user?.role==='teacher'; const [items,setItems]=useState<any[]>([]); const [selected,setSelected]=useState<any|null>(null); const [answer,setAnswer]=useState(''); const [feedback,setFeedback]=useState(''); const [score,setScore]=useState('');
  const load=async()=>{if(!supabase||!user?.uid)return; if(isTeacher){const {data}=await supabase.from('assignments').select('*').eq('teacher_id',user.uid).order('due_at',{ascending:true});setItems(data||[]);}else{const {data}=await supabase.from('assignments').select('*, assignment_submissions(*)').order('due_at',{ascending:true});setItems(data||[]);}}; useEffect(()=>{void load()},[user?.uid,isTeacher]);
  const submit=async()=>{if(!supabase||!user?.uid||!selected||!answer.trim())return;const status=selected.due_at&&new Date(selected.due_at)<new Date()?'late':'submitted';await supabase.from('assignment_submissions').upsert({assignment_id:selected.id,student_id:user.uid,answer_text:answer.trim(),status,submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'assignment_id,student_id'});setAnswer('');void load();};
  const grade=async(sub:any)=>{if(!supabase||!selected||user?.role!=='teacher')return;await supabase.from('assignment_submissions').update({status:'graded',score:Number(score),teacher_feedback:feedback,graded_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',sub.id); if(sub.student_id) await supabase.from('grade_records').insert({student_id:sub.student_id,teacher_id:user.uid,assignment_id:selected.id,title:selected.title,subject:selected.subject,score:Number(score),max_score:selected.max_score,notes:feedback});setScore('');setFeedback('');void load();};
  return <div className={shell} dir="rtl"><div><h1 className="text-2xl font-black text-[#1E3A8A]">الواجبات والملفات 📚</h1><p className="text-sm text-gray-500 mt-1">إنشاء الواجبات، تسليم الحل، التصحيح والدرجات.</p></div><div className="grid lg:grid-cols-[340px_1fr] gap-4"><div className={card}>{items.length===0?<p className="py-8 text-center text-gray-400">لا توجد واجبات.</p>:items.map(a=><button key={a.id} onClick={()=>setSelected(a)} className={`w-full text-right p-3 rounded-2xl mb-2 border ${selected?.id===a.id?'bg-blue-50 border-blue-200':'bg-gray-50 border-gray-100'}`}><div className="font-black text-sm">{a.title}</div><div className="text-[10px] text-gray-500 mt-1">{a.subject||'عام'} {a.due_at?`• التسليم ${new Date(a.due_at).toLocaleString('ar-EG')}`:''}</div></button>)}</div><div className={`${card} min-h-[480px]`}>{!selected?<div className="h-full flex items-center justify-center text-gray-400">اختر واجبًا.</div>:<div className="space-y-5"><div><h2 className="text-xl font-black">{selected.title}</h2><p className="text-sm text-gray-600 mt-2">{selected.description||'لا يوجد وصف.'}</p><div className="mt-3 flex gap-2 text-[10px] font-bold"><span className="px-2 py-1 rounded-lg bg-gray-50 border border-gray-200">الدرجة: {selected.max_score}</span><span className="px-2 py-1 rounded-lg bg-gray-50 border border-gray-200">المرفقات: {(selected.attachments||[]).length}</span></div></div>{!isTeacher?<div className="space-y-3"><textarea value={answer} onChange={e=>setAnswer(e.target.value)} className="w-full min-h-44 rounded-2xl border border-gray-200 p-4 text-sm" placeholder="اكتب الحل هنا..."/><button onClick={()=>void submit()} className="px-5 py-3 rounded-2xl bg-[#2563EB] text-white text-sm font-black">تسليم الواجب</button></div>:<div className="space-y-3">{(selected.assignment_submissions||[]).length===0?<p className="text-sm text-gray-400">لم يتم استلام تسليمات بعد.</p>:selected.assignment_submissions.map((s:any)=><div key={s.id} className="p-4 rounded-2xl bg-gray-50 border border-gray-200"><div className="flex justify-between gap-2"><span className="font-black text-sm">تسليم طالب</span><span className="text-[10px] text-gray-500">{s.status}</span></div><p className="text-sm mt-2 whitespace-pre-wrap">{s.answer_text||'مرفقات فقط'}</p><div className="grid sm:grid-cols-3 gap-2 mt-3"><input value={score} onChange={e=>setScore(e.target.value)} className="rounded-xl border p-2 text-xs" placeholder="الدرجة"/><input value={feedback} onChange={e=>setFeedback(e.target.value)} className="rounded-xl border p-2 text-xs sm:col-span-2" placeholder="ملاحظات المعلم"/><button onClick={()=>void grade(s)} className="sm:col-span-3 rounded-xl bg-emerald-600 text-white py-2 text-xs font-black">تصحيح وتسجيل الدرجة</button></div></div>)}</div>}</div>}</div></div></div>;
};

export const GradesPage: React.FC = () => {
  const { user }=useAuth(); const [rows,setRows]=useState<any[]>([]); useEffect(()=>{const run=async()=>{if(!supabase||!user?.uid)return;const {data}=await supabase.from('grade_records').select('*').eq('student_id',user.uid).order('recorded_at',{ascending:false});setRows(data||[])};void run()},[user?.uid]); const avg=useMemo(()=>rows.length?Math.round(rows.reduce((s,r)=>s+Number(r.score)/Number(r.max_score)*100,0)/rows.length):0,[rows]); return <div className={shell} dir="rtl"><div><h1 className="text-2xl font-black text-[#1E3A8A]">الدرجات والتقارير 📊</h1><p className="text-sm text-gray-500 mt-1">ملخص أداء واضح مع متوسط الدرجات وسجل التطور.</p></div><div className="grid grid-cols-2 md:grid-cols-3 gap-4"><div className={card}><div className="text-xs text-gray-500">متوسط الأداء</div><div className="text-3xl font-black text-[#2563EB] mt-1">{avg}%</div></div><div className={card}><div className="text-xs text-gray-500">عدد التقييمات</div><div className="text-3xl font-black text-[#1E3A8A] mt-1">{rows.length}</div></div><div className={card}><div className="text-xs text-gray-500">أفضل درجة</div><div className="text-3xl font-black text-emerald-600 mt-1">{rows.length?Math.round(Math.max(...rows.map(r=>Number(r.score)/Number(r.max_score)*100))):0}%</div></div></div><div className={card}>{rows.length===0?<div className="py-10 text-center text-gray-400">لم يتم تسجيل درجات بعد.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-gray-500 border-b"><th className="p-3 text-right">التقييم</th><th className="p-3">المادة</th><th className="p-3">الدرجة</th><th className="p-3">التاريخ</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b last:border-0"><td className="p-3 font-black">{r.title}</td><td className="p-3">{r.subject||'-'}</td><td className="p-3 font-black">{r.score} / {r.max_score}</td><td className="p-3 text-xs text-gray-500">{new Date(r.recorded_at).toLocaleDateString('ar-EG')}</td></tr>)}</tbody></table></div>}</div></div>;
};

export const AttendanceOverviewPage: React.FC = () => {
  const { user } = useAuth(); const [rows,setRows]=useState<any[]>([]); useEffect(()=>{const run=async()=>{if(!supabase||!user?.uid)return;const {data}=await supabase.from('attendance_records').select('*').eq('student_id',user.uid).order('date',{ascending:false}).order('time',{ascending:false});setRows(data||[])};void run()},[user?.uid]); const present=rows.filter(r=>r.status==='present').length; const late=rows.filter(r=>r.status==='late').length; const absent=rows.filter(r=>r.status==='absent').length; return <div className={shell} dir="rtl"><div><h1 className="text-2xl font-black text-[#1E3A8A]">سجل الحضور المتطور ✅</h1><p className="text-sm text-gray-500 mt-1">الدخول والخروج، التأخير، الغياب، والتسويات محفوظة كسجل زمني.</p></div><div className="grid grid-cols-3 gap-3"><div className={card}><div className="text-xs text-gray-500">حاضر</div><div className="text-2xl font-black text-emerald-600 mt-1">{present}</div></div><div className={card}><div className="text-xs text-gray-500">متأخر</div><div className="text-2xl font-black text-amber-600 mt-1">{late}</div></div><div className={card}><div className="text-xs text-gray-500">غائب</div><div className="text-2xl font-black text-red-600 mt-1">{absent}</div></div></div><div className={card}>{rows.length===0?<div className="py-10 text-center text-gray-400">لا يوجد سجل حضور حتى الآن.</div>:<div className="space-y-2">{rows.map(r=><div key={r.id} className="p-3 rounded-2xl bg-gray-50 border border-gray-100 flex items-center justify-between"><div><div className="font-black text-sm">{r.date} • {r.time}</div><div className="text-xs text-gray-500">{r.notes||'تسجيل حضور'}</div></div><span className={`px-2 py-1 rounded-lg text-[10px] font-black ${r.status==='present'?'bg-emerald-50 text-emerald-700':r.status==='late'?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700'}`}>{r.status==='present'?'حاضر':r.status==='late'?'متأخر':'غائب'}</span></div>)}</div>}</div></div>;
};
