import React,{useEffect,useMemo,useState} from 'react';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../lib/AuthContext';

const Card:React.FC<{title:string;value?:string;children?:React.ReactNode}> = ({title,value,children}) => <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-bold text-slate-500">{title}</div>{value!==undefined&&<div className="mt-2 text-2xl font-black text-[#1E3A8A]">{value}</div>}{children}</div>;
const Empty:React.FC<{text:string}> = ({text}) => <div className="rounded-3xl border border-dashed border-slate-300 bg-slate-50 p-10 text-center text-sm font-bold text-slate-500">{text}</div>;

export const AssistantDashboardPage:React.FC<{onNavigate:(path:string)=>void}> = ({onNavigate})=>{
 const {user}=useAuth(); const [groups,setGroups]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!supabase||!user?.uid)return; void (async()=>{const {data}=await supabase.from('student_groups').select('id,name,subject,grade,current_count,max_students,schedule,location,is_active').order('created_at',{ascending:false});setGroups(data||[]);setLoading(false)})()},[user?.uid]);
 const students=useMemo(()=>groups.reduce((n,g)=>n+Number(g.current_count||0),0),[groups]);
 return <div className="space-y-6"><div><h1 className="text-2xl font-black text-[#1E3A8A]">لوحة المساعد</h1><p className="mt-1 text-sm text-slate-500">إدارة المجموعات والطلاب حسب الصلاحيات التي منحها لك المدرس.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><Card title="المجموعات" value={String(groups.length)}/><Card title="الطلاب" value={String(students)}/><Card title="المجموعات النشطة" value={String(groups.filter(g=>g.is_active!==false).length)}/><Card title="الحساب" value="مساعد"/></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-5"><Card title="اختصارات"><div className="grid grid-cols-2 gap-3 mt-4">{[['/assistant/groups','المجموعات'],['/assistant/students','الطلاب'],['/assistant/attendance','الحضور'],['/assistant/payments','المصروفات']].map(([p,t])=><button key={p} onClick={()=>onNavigate(p)} className="rounded-2xl bg-slate-50 border border-slate-200 p-4 text-sm font-black text-[#1E3A8A] hover:bg-blue-50">{t}</button>)}</div></Card><Card title="حالة التشغيل"><p className="mt-3 text-sm leading-7 text-slate-600">الوصول هنا يعتمد على علاقة المساعد بالمدرس وصلاحيات الحساب. بيانات المصروفات تظل مخفية ما لم يمنح المدرس صلاحية المصروفات.</p></Card></div>{loading?<div className="text-sm text-slate-500">جاري تحميل لوحة المساعد...</div>:groups.length===0?<Empty text="لا توجد مجموعات متاحة لك حاليًا."/>:null}</div>;
};

export const AssistantGroupsPage:React.FC = ()=>{
 const [groups,setGroups]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!supabase)return; void (async()=>{const {data,error}=await supabase.from('student_groups').select('id,name,subject,grade,current_count,max_students,schedule,location,is_active');if(!error)setGroups(data||[]);setLoading(false)})()},[]);
 return <div className="space-y-5"><div><h1 className="text-2xl font-black text-[#1E3A8A]">المجموعات</h1><p className="mt-1 text-sm text-slate-500">المجموعات التي يعمل عليها حسابك.</p></div>{loading?<div className="text-sm text-slate-500">جاري التحميل...</div>:groups.length===0?<Empty text="لا توجد مجموعات متاحة."/>:<div className="grid grid-cols-1 xl:grid-cols-2 gap-4">{groups.map(g=><div key={g.id} className="rounded-3xl bg-white border border-slate-200 p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-lg text-slate-900">{g.name}</h3><p className="text-xs text-slate-500 mt-1">{g.subject||'مادة غير محددة'} • {g.grade||'المرحلة غير محددة'}</p></div><span className={`px-2 py-1 rounded-lg text-[10px] font-black ${g.is_active===false?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{g.is_active===false?'متوقفة':'نشطة'}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><div className="rounded-2xl bg-slate-50 p-3"><span className="text-slate-500">الطلاب</span><b className="block mt-1">{g.current_count||0} / {g.max_students||'-'}</b></div><div className="rounded-2xl bg-slate-50 p-3"><span className="text-slate-500">الموعد</span><b className="block mt-1">{g.schedule||'غير محدد'}</b></div></div><p className="mt-3 text-xs text-slate-500">{g.location||'الموقع غير محدد'}</p></div>)}</div>}</div>;
};

export const AssistantStudentsPage:React.FC = ()=>{
 const [students,setStudents]=useState<any[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!supabase)return;void(async()=>{const {data}=await supabase.from('group_enrollments').select('id,group_id,student_id,student_name,student_phone,parent_phone,grade,attendance_rate,total_sessions,attended_sessions,payment_status,status,avatar_url').order('enrolled_at',{ascending:false});setStudents(data||[]);setLoading(false)})()},[]);
 const filtered=useMemo(()=>students.filter(s=>(s.student_name||'').toLowerCase().includes(q.toLowerCase())||(s.student_phone||'').includes(q)),[students,q]);
 return <div className="space-y-5"><div><h1 className="text-2xl font-black text-[#1E3A8A]">الطلاب</h1><p className="mt-1 text-sm text-slate-500">بيانات الطلاب في المجموعات المسموح لك بإدارتها.</p></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث باسم الطالب أو الهاتف" className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-100"/>{loading?<div className="text-sm text-slate-500">جاري التحميل...</div>:filtered.length===0?<Empty text="لا يوجد طلاب مطابقون للبحث."/>:<div className="grid grid-cols-1 xl:grid-cols-2 gap-4">{filtered.map(s=><div key={s.id} className="rounded-3xl bg-white border border-slate-200 p-5"><div className="flex justify-between gap-3"><div><h3 className="font-black text-slate-900">{s.student_name}</h3><p className="mt-1 text-xs text-slate-500">{s.grade||'—'} • {s.student_phone||'بدون هاتف'}</p></div><span className="rounded-xl bg-blue-50 px-2.5 py-1 text-[10px] font-black text-blue-700">{s.status||'active'}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><div className="rounded-2xl bg-slate-50 p-3"><span className="text-slate-500">الحضور</span><b className="block mt-1">{s.attendance_rate??0}%</b></div><div className="rounded-2xl bg-slate-50 p-3"><span className="text-slate-500">الحصص</span><b className="block mt-1">{s.attended_sessions??0}/{s.total_sessions??0}</b></div><div className="rounded-2xl bg-slate-50 p-3"><span className="text-slate-500">المصروفات</span><b className="block mt-1">{s.payment_status||'غير محدد'}</b></div></div></div>)}</div>}</div>;
};

export const AssistantAttendancePage:React.FC = ()=>{
 const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!supabase)return;void(async()=>{const {data}=await supabase.from('attendance_records').select('id,student_name,date,time,status,late_minutes,checked_in_at,checked_out_at,group_id,is_makeup').order('date',{ascending:false}).order('time',{ascending:false}).limit(200);setRows(data||[]);setLoading(false)})()},[]);
 return <div className="space-y-5"><div><h1 className="text-2xl font-black text-[#1E3A8A]">الحضور والانصراف</h1><p className="mt-1 text-sm text-slate-500">سجل الحضور المتاح لك حسب صلاحيات المجموعات.</p></div>{loading?<div className="text-sm text-slate-500">جاري التحميل...</div>:rows.length===0?<Empty text="لا توجد سجلات حضور."/>:<div className="overflow-x-auto rounded-3xl border border-slate-200 bg-white"><table className="min-w-full text-xs"><thead className="bg-slate-50"><tr><th className="p-4 text-right">الطالب</th><th className="p-4 text-right">التاريخ</th><th className="p-4 text-right">الحالة</th><th className="p-4 text-right">دخول</th><th className="p-4 text-right">خروج</th><th className="p-4 text-right">تأخير</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="p-4 font-bold">{r.student_name}</td><td className="p-4">{r.date}</td><td className="p-4 font-bold">{r.status}</td><td className="p-4">{r.checked_in_at?new Date(r.checked_in_at).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'}):'—'}</td><td className="p-4">{r.checked_out_at?new Date(r.checked_out_at).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'}):'—'}</td><td className="p-4">{r.late_minutes||0} د</td></tr>)}</tbody></table></div>}</div>;
};

export const AssistantPaymentsPage:React.FC = ()=>{
 const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!supabase)return;void(async()=>{const {data}=await supabase.from('payment_records').select('id,student_id,group_id,invoice_number,amount,subject,billing_period,status,paid_at,created_at').order('created_at',{ascending:false}).limit(200);setRows(data||[]);setLoading(false)})()},[]);
 return <div className="space-y-5"><div><h1 className="text-2xl font-black text-[#1E3A8A]">المصروفات</h1><p className="mt-1 text-sm text-slate-500">تظهر هذه الصفحة فقط عندما يمنح المدرس حسابك صلاحية المصروفات.</p></div>{loading?<div className="text-sm text-slate-500">جاري التحميل...</div>:rows.length===0?<Empty text="لا توجد بيانات مصروفات أو لا توجد لديك صلاحية الوصول إليها."/>:<div className="overflow-x-auto rounded-3xl border border-slate-200 bg-white"><table className="min-w-full text-xs"><thead className="bg-slate-50"><tr><th className="p-4 text-right">الفاتورة</th><th className="p-4 text-right">المبلغ</th><th className="p-4 text-right">المادة</th><th className="p-4 text-right">الفترة</th><th className="p-4 text-right">الحالة</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="p-4 font-bold">{r.invoice_number||'—'}</td><td className="p-4">{Number(r.amount||0).toLocaleString('ar-EG')} ج.م</td><td className="p-4">{r.subject||'—'}</td><td className="p-4">{r.billing_period||'—'}</td><td className="p-4 font-bold">{r.status||'—'}</td></tr>)}</tbody></table></div>}</div>;
};

export const AssistantProfilePage:React.FC = ()=>{const {user}=useAuth(); return <div className="space-y-5"><div><h1 className="text-2xl font-black text-[#1E3A8A]">الملف الشخصي</h1><p className="mt-1 text-sm text-slate-500">بيانات حسابك كمساعد.</p></div><div className="rounded-3xl bg-white border border-slate-200 p-6"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm"><div><span className="text-slate-500 block mb-1">الاسم</span><b>{user?.name||'—'}</b></div><div><span className="text-slate-500 block mb-1">البريد</span><b>{user?.email||'—'}</b></div><div><span className="text-slate-500 block mb-1">الهاتف</span><b>{user?.phone||'—'}</b></div><div><span className="text-slate-500 block mb-1">المحافظة</span><b>{user?.governorate||'—'}</b></div></div></div></div>};
