import React, { useMemo, useState } from 'react';
import { Activity, BarChart3, BellRing, BookOpen, Calendar, ClipboardCheck, ClipboardList, FileCheck2, Home, Layers, LogOut, MessageCircle, QrCode, Receipt, ScanLine, Settings2, ShieldCheck, Star, UserCheck, UserCog, UserPlus, Users, WalletCards, UserPlus2, Shuffle, BookMarked, StickyNote } from 'lucide-react';
import { AccountRole } from '../../types';
import { useAuth } from '../../lib/AuthContext';
import { getCleanAvatarUrl } from '../../lib/avatarHelper';

type Item={name:string;path:string;icon:React.ComponentType<{className?:string}>;badge?:string;highlight?:boolean};
type Section={title:string;items:Item[]};
interface Props{currentRole:AccountRole;currentPath:string;onNavigate:(path:string)=>void;onLogout?:()=>void;}

const sections=(role:AccountRole):Section[]=>{
 if(role==='teacher') return [
  {title:'الرئيسية',items:[{name:'لوحة التحكم',path:'/teacher/dashboard',icon:Activity},{name:'الإشعارات',path:'/teacher/notifications',icon:BellRing},{name:'الرسائل',path:'/teacher/messages',icon:MessageCircle},{name:'التقويم',path:'/teacher/calendar',icon:Calendar}]},
  {title:'إدارة الطلاب',items:[{name:'الطلاب',path:'/teacher/students',icon:Users},{name:'المجموعات',path:'/teacher/groups',icon:Layers},{name:'الجلسات والحصص',path:'/teacher/sessions',icon:Calendar},{name:'طلبات التسجيل',path:'/teacher/enrollment-requests',icon:UserPlus2,highlight:true},{name:'النقل والتعويض',path:'/teacher/transfers',icon:Shuffle},{name:'الحضور',path:'/teacher/attendance',icon:UserCheck},{name:'مسح الحضور QR',path:'/teacher/scan',icon:ScanLine,highlight:true},{name:'الواجبات',path:'/teacher/assignments',icon:BookOpen},{name:'ملاحظات الطلاب',path:'/teacher/student-notes',icon:StickyNote}]},
  {title:'فريق العمل',items:[{name:'المساعدون',path:'/teacher/assistants',icon:UserPlus,highlight:true}]},
  {title:'الامتحانات والتقييم',items:[{name:'الامتحانات والتوزيع',path:'/teacher/exams',icon:FileCheck2,highlight:true},{name:'دفتر الدرجات',path:'/teacher/gradebook',icon:BookMarked},{name:'التقييمات',path:'/teacher/reviews',icon:Star}]},
  {title:'المال والملف',items:[{name:'المدفوعات والعمولة',path:'/teacher/payments',icon:WalletCards},{name:'المواعيد المتاحة',path:'/teacher/availability',icon:Calendar},{name:'الملف العام',path:'/teacher/profile',icon:UserCog}]},
 ];
 if(role==='assistant') return [{title:'المساعد',items:[{name:'الرئيسية',path:'/assistant/dashboard',icon:Activity},{name:'التوثيق',path:'/assistant/verification',icon:ShieldCheck,highlight:true},{name:'المجموعات',path:'/assistant/groups',icon:Layers},{name:'الطلاب',path:'/assistant/students',icon:Users},{name:'الحضور والانصراف',path:'/assistant/attendance',icon:UserCheck},{name:'المصروفات',path:'/assistant/payments',icon:Receipt},{name:'الدعوات',path:'/assistant/invitations',icon:UserPlus},{name:'الرسائل',path:'/assistant/messages',icon:MessageCircle},{name:'الإشعارات',path:'/assistant/notifications',icon:BellRing},{name:'التقويم',path:'/assistant/calendar',icon:Calendar},{name:'الملف الشخصي',path:'/assistant/profile',icon:UserCog}]}];
 if(role==='parent') return [{title:'ولي الأمر',items:[{name:'الرئيسية',path:'/parent/dashboard',icon:Activity},{name:'الإشعارات',path:'/parent/notifications',icon:BellRing},{name:'التقويم',path:'/parent/calendar',icon:Calendar},{name:'الرسائل',path:'/parent/messages',icon:MessageCircle},{name:'الدرجات',path:'/parent/grades',icon:BarChart3},{name:'سجل الحضور',path:'/parent/attendance',icon:ClipboardCheck},{name:'المدفوعات',path:'/parent/payments',icon:Receipt},{name:'الطلبات والموافقات',path:'/parent/requests',icon:ClipboardList,highlight:true},{name:'الإعدادات',path:'/parent/settings',icon:Settings2}]}];
 return [{title:'الطالب',items:[{name:'الرئيسية',path:'/student/dashboard',icon:Activity},{name:'الإشعارات',path:'/student/notifications',icon:BellRing},{name:'التقويم',path:'/student/calendar',icon:Calendar},{name:'الرسائل',path:'/student/messages',icon:MessageCircle},{name:'الواجبات',path:'/student/assignments',icon:BookOpen},{name:'الدرجات',path:'/student/grades',icon:BarChart3},{name:'نتائج الامتحانات',path:'/student/exam-results',icon:FileCheck2,highlight:true},{name:'الحضور',path:'/student/attendance',icon:ClipboardCheck},{name:'التقييمات',path:'/student/reviews',icon:Star},{name:'كارنيه QR',path:'/student/qr-card',icon:QrCode,badge:'رقمي'},{name:'الملف الشخصي',path:'/student/profile',icon:UserCog},{name:'مدرسيني',path:'/student/tutors',icon:Users},{name:'حجز حصة',path:'/student/book',icon:Calendar},{name:'المدفوعات',path:'/student/payments',icon:Receipt}]}];
};

export const DashboardSidebar:React.FC<Props>=({currentRole,currentPath,onNavigate,onLogout})=>{
 const {user}=useAuth(); const [open,setOpen]=useState(false); const groups=useMemo(()=>sections(currentRole),[currentRole]);
 const name=user?.name||(currentRole==='teacher'?'معلم حِصّتي':currentRole==='assistant'?'مساعد حِصّتي':currentRole==='parent'?'ولي أمر حِصّتي':'طالب حِصّتي');
 const roleLabel=currentRole==='teacher'?'حساب معلم':currentRole==='assistant'?'حساب مساعد':currentRole==='parent'?'حساب ولي أمر':'حساب طالب';
 const avatar=getCleanAvatarUrl(user?.avatarUrl||user?.profileData?.avatarUrl,currentRole,name);
 const Nav=()=> <nav className="space-y-5">{groups.map(g=><div key={g.title}><div className="px-3 mb-1.5 text-[10px] font-black text-slate-400">{g.title}</div><div className="space-y-1">{g.items.map(i=>{const Icon=i.icon,active=currentPath===i.path;return <button key={i.path+i.name} onClick={()=>{onNavigate(i.path);setOpen(false)}} className={`w-full flex items-center justify-between px-3.5 py-2.5 rounded-xl text-xs font-bold transition-all ${active?'bg-blue-600 text-white shadow-sm':i.highlight?'bg-emerald-50 text-emerald-800 border border-emerald-200 hover:bg-emerald-100':'text-slate-800 hover:bg-blue-50 hover:text-blue-600'}`}><span className="flex items-center gap-2.5 min-w-0"><Icon className={`w-4 h-4 shrink-0 ${active?'text-white':i.highlight?'text-emerald-700':'text-slate-400'}`}/><span className="truncate">{i.name}</span></span>{i.badge&&<span className="text-[9px] px-1.5 py-0.5 rounded-md bg-blue-50 text-blue-700">{i.badge}</span>}</button>})}</div></div>)}</nav>;
 return <><aside className="hidden lg:flex flex-col w-64 xl:w-72 bg-white border border-slate-200 rounded-3xl p-5 shrink-0 sticky top-24 h-[calc(100vh-8rem)] overflow-y-auto justify-between shadow-sm"><div><div className="p-3.5 bg-slate-50 border border-slate-200 rounded-2xl flex items-center gap-3 mb-6"><img src={avatar} alt={name} className="w-11 h-11 rounded-xl object-cover border border-white ring-2 ring-blue-100" referrerPolicy="no-referrer"/><div className="min-w-0"><span className="text-[10px] font-bold text-slate-500 block">{roleLabel}</span><h3 className="text-xs font-black text-blue-900 truncate">{name}</h3></div></div><Nav/></div><div className="pt-4 mt-5 border-t border-slate-100 space-y-2"><button onClick={()=>onNavigate('/')} className="w-full flex items-center gap-2 px-3 py-2 text-xs font-bold text-slate-600 hover:bg-blue-50 rounded-xl"><Home className="w-4 h-4"/>العودة للرئيسية</button>{onLogout&&<button onClick={onLogout} className="w-full flex items-center gap-2 px-3 py-2 text-xs font-bold text-red-600 hover:bg-red-50 rounded-xl"><LogOut className="w-4 h-4"/>تسجيل الخروج</button>}</div></aside><button aria-label="فتح القائمة" onClick={()=>setOpen(true)} className="lg:hidden fixed top-20 right-4 z-30 rounded-2xl bg-slate-900 text-white p-3 shadow-lg"><Layers className="w-5 h-5"/></button>{open&&<div className="lg:hidden fixed inset-0 z-50 bg-slate-950/45" onClick={()=>setOpen(false)}><aside onClick={e=>e.stopPropagation()} dir="rtl" className="absolute right-0 top-0 bottom-0 w-[min(88vw,360px)] bg-white shadow-2xl p-4 overflow-y-auto"><div className="flex items-center justify-between mb-5"><div className="font-black text-sm">قائمة لوحة التحكم</div><button onClick={()=>setOpen(false)} className="rounded-xl bg-slate-100 px-3 py-2 font-black">×</button></div><div className="p-3 bg-slate-50 border rounded-2xl flex items-center gap-3 mb-5"><img src={avatar} alt={name} className="w-10 h-10 rounded-xl object-cover"/><div><div className="text-[10px] text-slate-500 font-bold">{roleLabel}</div><div className="text-xs font-black text-blue-900">{name}</div></div></div><Nav/></aside></div>}</>;
};
