import React,{useEffect,useMemo,useState} from 'react';
import {AlertCircle,Calendar,CheckCircle2,Clock3,Plus,RefreshCw,Users,X} from 'lucide-react';
import {useAuth} from '../../lib/AuthContext';
import {getCleanAvatarUrl} from '../../lib/avatarHelper';
import {findStudentByCodeOrPhone,sendParentLinkRequest,subscribeToParentRequests,ParentLinkRequest,removeParentChildLink} from '../../lib/parentStudentService';
import {supabase} from '../../lib/supabase';
import {StatCard} from '../../components/common/ui';

export const ParentDashboardPageV2:React.FC<{onNavigate:(path:string)=>void}>=({onNavigate})=>{
 const {user}=useAuth(); const uid=user?.uid||''; const [children,setChildren]=useState<any[]>([]); const [requests,setRequests]=useState<ParentLinkRequest[]>([]); const [selected,setSelected]=useState(''); const [attendance,setAttendance]=useState<any[]>([]); const [bookings,setBookings]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [modal,setModal]=useState(false); const [query,setQuery]=useState(''); const [found,setFound]=useState<any|null>(null); const [msg,setMsg]=useState<{kind:'success'|'error';text:string}|null>(null);
 const load=async()=>{if(!uid||!supabase){setLoading(false);return;} setRefreshing(true); try{const childIdRes=await supabase.from('parent_children').select('child_id').eq('parent_id',uid); const childIds=(childIdRes.data||[]).map((r:any)=>r.child_id); const [{data:links,error:lerr},{data:reqs,error:rerr},{data:atts,error:aerr},{data:bks,error:berr}]=await Promise.all([supabase.from('parent_children').select('id,parent_id,child_id,child_name,child_qr_code,created_at').eq('parent_id',uid).order('created_at',{ascending:false}),supabase.from('parent_link_requests').select('*').eq('parent_id',uid).order('created_at',{ascending:false}),childIds.length?supabase.from('attendance_records').select('id,student_id,status,date,time,group_id').in('student_id',childIds).order('date',{ascending:false}).limit(100):Promise.resolve<any>({data:[]}),childIds.length?supabase.from('booking_requests').select('id,student_id,tutor_id,subject,day,time,location,status,price,created_at').in('student_id',childIds).order('created_at',{ascending:false}).limit(50):Promise.resolve<any>({data:[]})]); if(lerr)throw lerr;if(rerr)throw rerr;if(aerr)throw aerr;if(berr)throw berr; let profs:any[]=[]; if(childIds.length){const {data,error}=await supabase.from('profiles').select('id,full_name,phone,avatar_url,grade,governorate,city,qr_code').in('id',childIds);if(error)throw error;profs=data||[];} const pmap=new Map(profs.map(p=>[p.id,p])); setChildren((links||[]).map((x:any)=>{const p=pmap.get(x.child_id)||{};return {...x,name:p.full_name||x.child_name||'طالب',grade:p.grade||'غير محدد',avatar:getCleanAvatarUrl(p.avatar_url,'student',p.full_name||x.child_name),qr:p.qr_code||x.child_qr_code||'',city:p.city||'',governorate:p.governorate||''}})); setRequests(reqs||[]); setAttendance(atts||[]); setBookings(bks||[]); }catch(e:any){setMsg({kind:'error',text:e?.message||'تعذر تحميل بيانات الأبناء.'});}finally{setLoading(false);setRefreshing(false);}};
 useEffect(()=>{void load();},[uid]); useEffect(()=>{if(!uid)return subscribeToParentRequests(uid,setRequests);},[uid]);
 const current=children.find(c=>c.child_id===selected)||children[0]; useEffect(()=>{if(!selected&&children[0])setSelected(children[0].child_id)},[children,selected]);
 const childAttendance=useMemo(()=>current?attendance.filter(a=>a.student_id===current.child_id):[],[attendance,current]); const rate=childAttendance.length?Math.round(childAttendance.filter(a=>a.status==='present'||a.status==='late').length/childAttendance.length*100):0; const childBookings=useMemo(()=>current?bookings.filter(b=>b.student_id===current.child_id):[],[bookings,current]);
 const search=async()=>{setFound(null);setMsg(null);const s=await findStudentByCodeOrPhone(query);if(s)setFound(s);else setMsg({kind:'error',text:'لم يتم العثور على طالب بهذا الكود أو الرقم.'});}; const link=async()=>{if(!found||!uid)return;const r=await sendParentLinkRequest({uid,name:user?.name||'ولي أمر',phone:user?.phone||'',email:user?.email||'',avatarUrl:user?.avatarUrl||''},found.qrCode);setMsg({kind:r.success?'success':'error',text:r.message});if(r.success){setModal(false);setFound(null);setQuery('');}};
 return <div className="space-y-4 text-right" dir="rtl">{msg&&<div className={`anim-up rounded-xl border p-3 flex justify-between items-center ${msg.kind==='success'?'bg-emerald-50 border-emerald-200 text-emerald-900':'bg-red-50 border-red-200 text-red-900'}`}><span className="text-xs font-bold flex gap-2 items-center">{msg.kind==='success'?<CheckCircle2 className="w-4 h-4"/>:<AlertCircle className="w-4 h-4"/>}{msg.text}</span><button onClick={()=>setMsg(null)} className="cursor-pointer"><X className="w-3.5 h-3.5"/></button></div>}
 <section className="anim-up hero-lux rounded-2xl p-4 sm:p-5 text-white flex flex-col sm:flex-row gap-3 justify-between"><div className="hero-dots" aria-hidden="true"/><div className="hero-blob w-40 h-40 -top-16 -right-14 animate-float-slow" aria-hidden="true"/><div className="hero-blob w-24 h-24 -bottom-10 -left-8 animate-float-reverse" aria-hidden="true"/><div className="relative"><h1 className="text-lg font-black drop-shadow-sm">لوحة ولي الأمر 👋</h1><p className="text-[11px] text-white/85 mt-1">بيانات أبنائك من حساباتهم الحقيقية على حِصّتي.</p></div><div className="relative flex gap-2"><button onClick={()=>void load()} className="rounded-xl bg-white/15 border border-white/30 backdrop-blur-sm px-3.5 py-2 text-[11px] font-bold flex gap-1.5 items-center text-white cursor-pointer hover:bg-white/30"><RefreshCw className={`w-3.5 h-3.5 ${refreshing?'animate-spin':''}`}/>تحديث</button><button onClick={()=>setModal(true)} className="rounded-xl bg-white text-[color:var(--role-color)] px-3.5 py-2 text-[11px] font-black flex gap-1.5 items-center cursor-pointer hover:bg-amber-50 shadow-lg hover:-translate-y-0.5"><Plus className="w-3.5 h-3.5"/>ربط ابن</button></div></section>
 <section className="anim-up card-lux bg-white border border-slate-200 rounded-2xl p-3.5" style={{animationDelay:'90ms'}}><div className="flex items-center justify-between gap-3 mb-2.5 px-1"><span className="text-[11px] font-black text-slate-700 flex items-center gap-1.5"><Users className="w-3.5 h-3.5 text-[color:var(--role-color)]"/>الأبناء المرتبطون<span className="text-[10px] font-bold text-slate-400">({children.length})</span></span><span className="text-[10px] text-slate-400">اختر الابن لمتابعة بياناته</span></div><div className="flex flex-wrap gap-2">{children.map((c,i)=><button key={c.child_id} onClick={()=>setSelected(c.child_id)} className={`px-3.5 py-2 rounded-xl text-xs font-black border cursor-pointer row-in ${current?.child_id===c.child_id?'chip-grad border-transparent':'bg-slate-50 text-slate-700 border-slate-200 hover:border-[color:var(--role-soft-border)] hover:-translate-y-0.5'}`} style={{animationDelay:`${Math.min(i*50,300)}ms`}}><div>{c.name}</div><div className="text-[10px] opacity-70 mt-0.5">{c.grade}</div></button>)}{children.length===0&&<div className="w-full py-6 text-center text-sm text-slate-500">لا يوجد أبناء مرتبطون بعد. استخدم «ربط ابن» لبدء الطلب.</div>}</div></section>
 {current&&<><section className="anim-up hero-lux rounded-2xl p-4 text-white" style={{animationDelay:'150ms'}}><div className="hero-dots" aria-hidden="true"/><div className="hero-blob w-32 h-32 -top-12 -left-10 animate-float-slow" aria-hidden="true"/><div className="relative flex items-center gap-3"><img src={current.avatar} alt={current.name} className="w-12 h-12 rounded-xl object-cover border-2 border-white/60"/><div><h2 className="text-base font-black drop-shadow-sm">{current.name}</h2><p className="text-[11px] text-white/85 mt-0.5">{current.grade}{current.governorate?` • ${current.governorate}`:''}{current.city?` • ${current.city}`:''}</p><p className="text-[10px] text-white/75 mt-1 font-mono">{current.qr}</p></div></div></section><section className="grid grid-cols-2 lg:grid-cols-4 gap-3" style={{animationDelay:'0ms'}}><StatCard delay={210} label="نسبة الحضور" value={`${rate}%`} tone="emerald" icon={<CheckCircle2 className="w-3.5 h-3.5"/>}/><StatCard delay={260} label="سجل الحضور" value={childAttendance.length} tone="blue" icon={<Clock3 className="w-3.5 h-3.5"/>}/><StatCard delay={310} label="الحجوزات" value={childBookings.length} tone="violet" icon={<Calendar className="w-3.5 h-3.5"/>}/><StatCard delay={360} label="المدرسون" value={new Set(childBookings.map(b=>b.tutor_id).filter(Boolean)).size} tone="amber" icon={<Users className="w-3.5 h-3.5"/>}/></section><section className="grid grid-cols-1 lg:grid-cols-2 gap-4"><Panel title="آخر الحضور">{childAttendance.length?childAttendance.slice(0,8).map((a,i)=><div key={a.id} className="row-in flex justify-between border-b last:border-0 py-2.5 hover:bg-[color:var(--role-soft)]/50 rounded-lg px-1" style={{animationDelay:`${Math.min(i*45,360)}ms`}}><div><div className="font-bold text-xs">{a.date}</div><div className="text-[11px] text-slate-500">{a.time||''}</div></div><span className={`text-xs font-black ${a.status==='present'?'text-emerald-700':a.status==='late'?'text-amber-700':'text-red-700'}`}>{a.status==='present'?'حاضر':a.status==='late'?'متأخر':'غائب'}</span></div>):<Empty text="لا يوجد سجل حضور حتى الآن."/>}</Panel><Panel title="الحجوزات الأخيرة">{childBookings.length?childBookings.slice(0,8).map((b,i)=><div key={b.id} className="row-in py-2.5 border-b last:border-0 hover:bg-[color:var(--role-soft)]/50 rounded-lg px-1" style={{animationDelay:`${Math.min(i*45,360)}ms`}}><div className="flex justify-between"><span className="font-black text-xs">{b.subject||'حصة'}</span><span className="text-[10px] font-bold">{b.status==='approved'?'مؤكد':b.status==='pending'?'قيد المراجعة':'مرفوض'}</span></div><div className="text-[11px] text-slate-500 mt-0.5 flex gap-3"><span><Calendar className="w-3 h-3 inline"/> {b.day||''}</span><span><Clock3 className="w-3 h-3 inline"/> {b.time||''}</span><span>{b.location||''}</span></div></div>):<Empty text="لا توجد حجوزات حتى الآن." action={()=>onNavigate('/student/book')}/>}</Panel></section></>}
 {requests.filter(r=>r.status==='pending').length>0&&<section className="anim-up rounded-2xl border border-amber-200 bg-amber-50 p-3.5" style={{animationDelay:'430ms'}}><div className="font-black text-[13px] text-amber-900">طلبات الربط المعلقة</div>{requests.filter(r=>r.status==='pending').map(r=><div key={r.id} className="mt-2 text-[11px] text-amber-800">طلب {r.studentName} — في انتظار موافقة الطالب.</div>)}</section>}
 {modal&&<div className="anim-fade fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4"><div className="dialog-lux w-full max-w-md bg-white rounded-2xl p-4"><div className="flex justify-between items-center"><h3 className="font-black text-base">ربط ابن جديد</h3><button onClick={()=>setModal(false)} className="cursor-pointer"><X/></button></div><p className="text-[11px] text-slate-500 mt-1">أدخل كود QR الطالب أو رقم هاتفه.</p><div className="flex gap-2 mt-4"><input value={query} onChange={e=>setQuery(e.target.value)} className="flex-1 rounded-xl border px-3 py-2.5 font-mono text-sm" placeholder="HASSTY-..." dir="ltr"/><button onClick={()=>void search()} className="rounded-xl chip-grad text-white px-4 font-bold text-xs cursor-pointer hover:-translate-y-0.5">بحث</button></div>{found&&<div className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3"><div className="font-black text-sm">{found.name}</div><div className="text-[11px] text-slate-600 mt-0.5">{found.grade||'طالب'} • {found.qrCode}</div><button onClick={()=>void link()} className="w-full mt-2.5 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 text-white py-2.5 text-xs font-black cursor-pointer shadow-md shadow-emerald-500/25 hover:-translate-y-0.5">إرسال طلب الربط</button></div>}</div></div>}
 </div>;
};
const Panel=({title,children}:{title:string;children:React.ReactNode})=><section className="card-lux anim-up bg-white border border-slate-200 rounded-2xl p-4" style={{animationDelay:'390ms'}}><h3 className="text-sm font-black text-slate-900 mb-2.5 flex items-center gap-2"><span className="bg-grad w-2 h-2 rounded-full" aria-hidden="true"/>{title}</h3>{children}</section>;
const Empty=({text,action}:{text:string;action?:()=>void})=><div className="py-6 text-center text-slate-500 text-xs font-bold">{text}{action&&<button onClick={action} className="block mx-auto mt-2.5 chip-grad rounded-xl px-4 py-2 cursor-pointer hover:-translate-y-0.5">ابدأ الآن</button>}</div>;
