import React,{useEffect,useMemo,useState} from 'react';
import {AlertCircle,Calendar,CheckCircle2,Clock3,MapPin,Plus,RefreshCw,Users,WalletCards,X} from 'lucide-react';
import {useAuth} from '../../lib/AuthContext';
import {getCleanAvatarUrl} from '../../lib/avatarHelper';
import {findStudentByCodeOrPhone,sendParentLinkRequest,subscribeToParentRequests,ParentLinkRequest,removeParentChildLink} from '../../lib/parentStudentService';
import {supabase} from '../../lib/supabase';

export const ParentDashboardPageV2:React.FC<{onNavigate:(path:string)=>void}>=({onNavigate})=>{
 const {user}=useAuth(); const uid=user?.uid||''; const [children,setChildren]=useState<any[]>([]); const [requests,setRequests]=useState<ParentLinkRequest[]>([]); const [selected,setSelected]=useState(''); const [attendance,setAttendance]=useState<any[]>([]); const [bookings,setBookings]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [modal,setModal]=useState(false); const [query,setQuery]=useState(''); const [found,setFound]=useState<any|null>(null); const [msg,setMsg]=useState<{kind:'success'|'error';text:string}|null>(null);
 const load=async()=>{if(!uid||!supabase){setLoading(false);return;} setRefreshing(true); try{const [{data:links,error:lerr},{data:reqs,error:rerr},{data:atts,error:aerr},{data:bks,error:berr}]=await Promise.all([supabase.from('parent_children').select('id,parent_id,child_id,child_name,child_qr_code,created_at').eq('parent_id',uid).order('created_at',{ascending:false}),supabase.from('parent_link_requests').select('*').eq('parent_id',uid).order('created_at',{ascending:false}),supabase.from('attendance_records').select('id,student_id,status,date,time,group_id').in('student_id', (await supabase.from('parent_children').select('child_id').eq('parent_id',uid)).data?.map((r:any)=>r.child_id)||[]).order('date',{ascending:false}).limit(100),supabase.from('booking_requests').select('id,student_id,tutor_id,subject,day,time,location,status,price,created_at').in('student_id',(await supabase.from('parent_children').select('child_id').eq('parent_id',uid)).data?.map((r:any)=>r.child_id)||[]).order('created_at',{ascending:false}).limit(50)]); if(lerr)throw lerr;if(rerr)throw rerr;if(aerr)throw aerr;if(berr)throw berr; const childIds=(links||[]).map((x:any)=>x.child_id); let profs:any[]=[]; if(childIds.length){const {data,error}=await supabase.from('profiles').select('id,full_name,phone,avatar_url,grade,governorate,city,qr_code').in('id',childIds);if(error)throw error;profs=data||[];} const pmap=new Map(profs.map(p=>[p.id,p])); setChildren((links||[]).map((x:any)=>{const p=pmap.get(x.child_id)||{};return {...x,name:p.full_name||x.child_name||'طالب',grade:p.grade||'غير محدد',avatar:getCleanAvatarUrl(p.avatar_url,'student',p.full_name||x.child_name),qr:p.qr_code||x.child_qr_code||'',city:p.city||'',governorate:p.governorate||''}})); setRequests(reqs||[]); setAttendance(atts||[]); setBookings(bks||[]); }catch(e:any){setMsg({kind:'error',text:e?.message||'تعذر تحميل بيانات الأبناء.'});}finally{setLoading(false);setRefreshing(false);}};
 useEffect(()=>{void load();},[uid]); useEffect(()=>{if(!uid)return subscribeToParentRequests(uid,setRequests);},[uid]);
 const current=children.find(c=>c.child_id===selected)||children[0]; useEffect(()=>{if(!selected&&children[0])setSelected(children[0].child_id)},[children,selected]);
 const childAttendance=useMemo(()=>current?attendance.filter(a=>a.student_id===current.child_id):[],[attendance,current]); const rate=childAttendance.length?Math.round(childAttendance.filter(a=>a.status==='present'||a.status==='late').length/childAttendance.length*100):0; const childBookings=useMemo(()=>current?bookings.filter(b=>b.student_id===current.child_id):[],[bookings,current]);
 const search=async()=>{setFound(null);setMsg(null);const s=await findStudentByCodeOrPhone(query);if(s)setFound(s);else setMsg({kind:'error',text:'لم يتم العثور على طالب بهذا الكود أو الرقم.'});}; const link=async()=>{if(!found||!uid)return;const r=await sendParentLinkRequest({uid,name:user?.name||'ولي أمر',phone:user?.phone||'',email:user?.email||'',avatarUrl:user?.avatarUrl||''},found.qrCode);setMsg({kind:r.success?'success':'error',text:r.message});if(r.success){setModal(false);setFound(null);setQuery('');}};
 return <div className="space-y-6 text-right" dir="rtl">{msg&&<div className={`rounded-2xl border p-4 flex justify-between ${msg.kind==='success'?'bg-emerald-50 border-emerald-200 text-emerald-900':'bg-red-50 border-red-200 text-red-900'}`}><span className="text-sm font-bold flex gap-2 items-center">{msg.kind==='success'?<CheckCircle2 className="w-5 h-5"/>:<AlertCircle className="w-5 h-5"/>}{msg.text}</span><button onClick={()=>setMsg(null)}><X className="w-4 h-4"/></button></div>}
 <section className="bg-white border border-slate-200 rounded-3xl p-5"><div className="flex flex-col sm:flex-row gap-3 justify-between"><div><h1 className="text-2xl font-black text-slate-900">لوحة ولي الأمر 👋</h1><p className="text-xs text-slate-500 mt-1">بيانات أبنائك من حساباتهم الحقيقية على HASSTY.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-xl border px-4 py-2 text-xs font-bold flex gap-2 items-center"><RefreshCw className={`w-4 h-4 ${refreshing?'animate-spin':''}`}/>تحديث</button><button onClick={()=>setModal(true)} className="rounded-xl bg-blue-600 text-white px-4 py-2 text-xs font-black flex gap-2 items-center"><Plus className="w-4 h-4"/>ربط ابن</button></div></div></section>
 <section className="bg-white border border-slate-200 rounded-3xl p-4"><div className="flex flex-wrap gap-2">{children.map(c=><button key={c.child_id} onClick={()=>setSelected(c.child_id)} className={`px-4 py-3 rounded-2xl text-xs font-black border ${current?.child_id===c.child_id?'bg-blue-600 text-white border-blue-600':'bg-slate-50 text-slate-700 border-slate-200'}`}><div>{c.name}</div><div className="text-[10px] opacity-70 mt-1">{c.grade}</div></button>)}{children.length===0&&<div className="w-full py-8 text-center text-sm text-slate-500">لا يوجد أبناء مرتبطون بعد. استخدم «ربط ابن» لبدء الطلب.</div>}</div></section>
 {current&&<><section className="bg-[#1E3A8A] text-white rounded-3xl p-6"><div className="flex items-center gap-4"><img src={current.avatar} alt={current.name} className="w-16 h-16 rounded-2xl object-cover border-2 border-white/30"/><div><h2 className="text-xl font-black">{current.name}</h2><p className="text-xs text-blue-100 mt-1">{current.grade}{current.governorate?` • ${current.governorate}`:''}{current.city?` • ${current.city}`:''}</p><p className="text-[11px] text-blue-100/80 mt-2 font-mono">{current.qr}</p></div></div></section><section className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Stat label="نسبة الحضور" value={`${rate}%`} icon={<CheckCircle2/>}/><Stat label="سجل الحضور" value={childAttendance.length} icon={<Clock3/>}/><Stat label="الحجوزات" value={childBookings.length} icon={<Calendar/>}/><Stat label="المدرسون" value={new Set(childBookings.map(b=>b.tutor_id).filter(Boolean)).size} icon={<Users/>}/></section><section className="grid grid-cols-1 lg:grid-cols-2 gap-5"><Panel title="آخر الحضور">{childAttendance.length?childAttendance.slice(0,8).map(a=><div key={a.id} className="flex justify-between border-b last:border-0 py-3"><div><div className="font-bold text-xs">{a.date}</div><div className="text-[11px] text-slate-500">{a.time||''}</div></div><span className={`text-xs font-black ${a.status==='present'?'text-emerald-700':a.status==='late'?'text-amber-700':'text-red-700'}`}>{a.status==='present'?'حاضر':a.status==='late'?'متأخر':'غائب'}</span></div>):<Empty text="لا يوجد سجل حضور حتى الآن."/>}</Panel><Panel title="الحجوزات الأخيرة">{childBookings.length?childBookings.slice(0,8).map(b=><div key={b.id} className="py-3 border-b last:border-0"><div className="flex justify-between"><span className="font-black text-xs">{b.subject||'حصة'}</span><span className="text-[10px] font-bold">{b.status==='approved'?'مؤكد':b.status==='pending'?'قيد المراجعة':'مرفوض'}</span></div><div className="text-[11px] text-slate-500 mt-1 flex gap-3"><span><Calendar className="w-3 h-3 inline"/> {b.day||''}</span><span><Clock3 className="w-3 h-3 inline"/> {b.time||''}</span><span>{b.location||''}</span></div></div>):<Empty text="لا توجد حجوزات حتى الآن." action={()=>onNavigate('/student/book')}/>}</Panel></section></>}
 {requests.filter(r=>r.status==='pending').length>0&&<section className="rounded-3xl border border-amber-200 bg-amber-50 p-4"><div className="font-black text-sm text-amber-900">طلبات الربط المعلقة</div>{requests.filter(r=>r.status==='pending').map(r=><div key={r.id} className="mt-3 text-xs text-amber-800">طلب {r.studentName} — في انتظار موافقة الطالب.</div>)}</section>}
 {modal&&<div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4"><div className="w-full max-w-md bg-white rounded-3xl p-5"><div className="flex justify-between items-center"><h3 className="font-black text-lg">ربط ابن جديد</h3><button onClick={()=>setModal(false)}><X/></button></div><p className="text-xs text-slate-500 mt-1">أدخل كود QR الطالب أو رقم هاتفه.</p><div className="flex gap-2 mt-5"><input value={query} onChange={e=>setQuery(e.target.value)} className="flex-1 rounded-xl border px-3 py-3 font-mono" placeholder="HASSTY-..." dir="ltr"/><button onClick={()=>void search()} className="rounded-xl bg-blue-600 text-white px-4 font-bold text-xs">بحث</button></div>{found&&<div className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="font-black">{found.name}</div><div className="text-xs text-slate-600 mt-1">{found.grade||'طالب'} • {found.qrCode}</div><button onClick={()=>void link()} className="w-full mt-3 rounded-xl bg-emerald-600 text-white py-3 text-xs font-black">إرسال طلب الربط</button></div>}</div></div>}
 </div>;
};
const Stat=({label,value,icon}:{label:string;value:string|number;icon:React.ReactNode})=><div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex justify-between text-slate-500 text-xs font-bold"><span>{label}</span><span className="text-blue-600">{icon}</span></div><div className="text-2xl font-black text-slate-900 mt-2">{value}</div></div>;
const Panel=({title,children}:{title:string;children:React.ReactNode})=><section className="bg-white border border-slate-200 rounded-3xl p-5"><h3 className="font-black text-slate-900 mb-3">{title}</h3>{children}</section>;
const Empty=({text,action}:{text:string;action?:()=>void})=><div className="py-8 text-center text-slate-500 text-xs font-bold">{text}{action&&<button onClick={action} className="block mx-auto mt-3 bg-blue-600 text-white rounded-xl px-4 py-2">ابدأ الآن</button>}</div>;
